--May 1, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-1-2013', 'NYM', 'New York', 'Mets', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-1-2013', 'MIN', 'Minnesota', 'Twins', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-1-2013', 'PIT', 'Pittsburgh', 'Pirates', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-1-2013', 'CIN', 'Cincinatti', 'Reds', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-1-2013', 'LAA', 'Anaheim', 'Angels', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-1-2013', 'HOU', 'Houston', 'Astros', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-1-2013', 'PHI', 'Philadelphia', 'Phillies', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-1-2013', 'BOS', 'Boston', 'Red Sox', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-1-2013', 'WSH', 'Washington D.C.', 'Nationals', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-1-2013', 'CHW', 'Chicago', 'White Sox', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-1-2013', 'SD', 'San Diego', 'Padres', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-1-2013', 'TB', 'Tampa Bay', 'Rays', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-1-2013', 'SF', 'San Francisco', 'Giants', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-1-2013', 'BAL', 'Baltimore', 'Orioles', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-1-2013', 'COL', 'Colorado', 'Rockies', 'LAD', 'Los Angeles', 'Dodgers');



--May 2, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-2-2013', 'TB', 'Tampa Bay', 'Rays', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-2-2013', 'SD', 'San Diego', 'Padres', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-2-2013', 'MIA', 'Miami', 'Marlins', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-2-2013', 'BOS', 'Boston', 'Red Sox', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-2-2013', 'WSH', 'Washington D.C.', 'Nationals', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-2-2013', 'CHW', 'Chicago', 'White Sox', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-2-2013', 'DET', 'Detroit', 'Tigers', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-2-2013', 'STL', 'St. Louis', 'Cardinals', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-2-2013', 'BAL', 'Baltimore', 'Orioles', 'LAA', 'Anaheim', 'Angels');



--May 3, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-3-2013', 'CIN', 'Cincinatti', 'Reds', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-3-2013', 'MIA', 'Miami', 'Marlins', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-3-2013', 'MIN', 'Minnesota', 'Twins', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-3-2013', 'OAK', 'Oakland', 'Athletics', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-3-2013', 'WSH', 'Washington D.C.', 'Nationals', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-3-2013', 'SEA', 'Seattle', 'Mariners', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-3-2013', 'NYM', 'New York', 'Mets', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-3-2013', 'BOS', 'Boston', 'Red Sox', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-3-2013', 'CHW', 'Chicago', 'White Sox', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-3-2013', 'DET', 'Detroit', 'Tigers', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-3-2013', 'STL', 'St. Louis', 'Cardinals', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-3-2013', 'TB', 'Tampa Bay', 'Rays', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-3-2013', 'BAL', 'Baltimore', 'Orioles', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-3-2013', 'ARI', 'Arizona', 'Diamondbacks', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-3-2013', 'LAD', 'Los Angeles', 'Dodgers', 'SF', 'San Francisco', 'Giants');
--May 4, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-4-2013', 'CIN', 'Cincinatti', 'Reds', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-4-2013', 'MIN', 'Minnesota', 'Twins', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-4-2013', 'OAK', 'Oakland', 'Athletics', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-4-2013', 'SEA', 'Seattle', 'Mariners', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-4-2013', 'BAL', 'Baltimore', 'Orioles', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-4-2013', 'STL', 'St. Louis', 'Cardinals', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-4-2013', 'WSH', 'Washington D.C.', 'Nationals', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-4-2013', 'MIA', 'Miami', 'Marlins', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-4-2013', 'CHW', 'Chicago', 'White Sox', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-4-2013', 'DET', 'Detroit', 'Tigers', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-4-2013', 'NYM', 'New York', 'Mets', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-4-2013', 'BOS', 'Boston', 'Red Sox', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-4-2013', 'TB', 'Tampa Bay', 'Rays', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-4-2013', 'ARI', 'Arizona', 'Diamondbacks', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-4-2013', 'LAD', 'Los Angeles', 'Dodgers', 'SF', 'San Francisco', 'Giants');
--May 5, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-5-2013', 'MIN', 'Minnesota', 'Twins', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-5-2013', 'OAK', 'Oakland', 'Athletics', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-5-2013', 'SEA', 'Seattle', 'Mariners', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-5-2013', 'NYM', 'New York', 'Mets', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-5-2013', 'WSH', 'Washington D.C.', 'Nationals', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-5-2013', 'CHW', 'Chicago', 'White Sox', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-5-2013', 'STL', 'St. Louis', 'Cardinals', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-5-2013', 'CIN', 'Cincinatti', 'Reds', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-5-2013', 'MIA', 'Miami', 'Marlins', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-5-2013', 'BOS', 'Boston', 'Red Sox', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-5-2013', 'BAL', 'Baltimore', 'Orioles', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-5-2013', 'ARI', 'Arizona', 'Diamondbacks', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-5-2013', 'DET', 'Detroit', 'Tigers', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-5-2013', 'TB', 'Tampa Bay', 'Rays', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-5-2013', 'LAD', 'Los Angeles', 'Dodgers', 'SF', 'San Francisco', 'Giants');
--May 6, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-6-2013', 'CHW', 'Chicago', 'White Sox', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-6-2013', 'OAK', 'Oakland', 'Athletics', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-6-2013', 'ATL', 'Atlanta', 'Braves', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-6-2013', 'MIN', 'Minnesota', 'Twins', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-6-2013', 'TOR', 'Toronto', 'Blue Jays', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-6-2013', 'TEX', 'Texas', 'Rangers', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-6-2013', 'ARI', 'Arizona', 'Diamondbacks', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-6-2013', 'MIA', 'Miami', 'Marlins', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-6-2013', 'PHI', 'Philadelphia', 'Phillies', 'SF', 'San Francisco', 'Giants');




--May 7, 2013DETDET
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-7-2013', 'DET', 'Detroit', 'Tigers', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-7-2013', 'KC', 'Kansas City', 'Royals', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-7-2013', 'OAK', 'Oakland', 'Athletics', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-7-2013', 'SEA', 'Seattle', 'Mariners', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-7-2013', 'ATL', 'Atlanta', 'Braves', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-7-2013', 'CHW', 'Chicago', 'White Sox', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-7-2013', 'MIN', 'Minnesota', 'Twins', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-7-2013', 'TOR', 'Toronto', 'Blue Jays', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-7-2013', 'STL', 'St. Louis', 'Cardinals', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-7-2013', 'LAA', 'Anaheim', 'Angels', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-7-2013', 'TEX', 'Texas', 'Rangers', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-7-2013', 'NYY', 'New York', 'Yankees', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-7-2013', 'ARI', 'Arizona', 'Diamondbacks', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-7-2013', 'MIA', 'Miami', 'Marlins', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-7-2013', 'PHI', 'Philadelphia', 'Phillies', 'SF', 'San Francisco', 'Giants');
--May 8, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-8-2013', 'ATL', 'Atlanta', 'Braves', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-8-2013', 'SEA', 'Seattle', 'Mariners', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-8-2013', 'STL', 'St. Louis', 'Cardinals', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-8-2013', 'MIA', 'Miami', 'Marlins', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-8-2013', 'PHI', 'Philadelphia', 'Phillies', 'SF', 'San Francisco', 'Giants');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-8-2013', 'DET', 'Detroit', 'Tigers', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-8-2013', 'KC', 'Kansas City', 'Royals', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-8-2013', 'OAK', 'Oakland', 'Athletics', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-8-2013', 'CHW', 'Chicago', 'White Sox', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-8-2013', 'MIN', 'Minnesota', 'Twins', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-8-2013', 'TOR', 'Toronto', 'Blue Jays', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-8-2013', 'LAA', 'Anaheim', 'Angels', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-8-2013', 'TEX', 'Texas', 'Rangers', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-8-2013', 'NYY', 'New York', 'Yankees', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-8-2013', 'ARI', 'Arizona', 'Diamondbacks', 'LAD', 'Los Angeles', 'Dodgers');
--May 9, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-9-2013', 'OAK', 'Oakland', 'Athletics', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-9-2013', 'NYY', 'New York', 'Yankees', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-9-2013', 'DET', 'Detroit', 'Tigers', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-9-2013', 'KC', 'Kansas City', 'Royals', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-9-2013', 'MIN', 'Minnesota', 'Twins', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-9-2013', 'PIT', 'Pittsburgh', 'Pirates', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-9-2013', 'TOR', 'Toronto', 'Blue Jays', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-9-2013', 'LAA', 'Anaheim', 'Angels', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-9-2013', 'PHI', 'Philadelphia', 'Phillies', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-9-2013', 'ATL', 'Atlanta', 'Braves', 'SF', 'San Francisco', 'Giants');




--May 10, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-10-2013', 'CHC', 'Chicago', 'Cubs', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-10-2013', 'CLE', 'Cleveland', 'Indians', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-10-2013', 'MIL', 'Milwaukee', 'Brewers', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-10-2013', 'PIT', 'Pittsburgh', 'Pirates', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-10-2013', 'SD', 'San Diego', 'Padres', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-10-2013', 'TOR', 'Toronto', 'Blue Jays', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-10-2013', 'LAA', 'Anaheim', 'Angels', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-10-2013', 'BAL', 'Baltimore', 'Orioles', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-10-2013', 'NYY', 'New York', 'Yankees', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-10-2013', 'TEX', 'Texas', 'Rangers', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-10-2013', 'COL', 'Colorado', 'Rockies', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-10-2013', 'PHI', 'Philadelphia', 'Phillies', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-10-2013', 'MIA', 'Miami', 'Marlins', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-10-2013', 'OAK', 'Oakland', 'Athletics', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-10-2013', 'ATL', 'Atlanta', 'Braves', 'SF', 'San Francisco', 'Giants');




--May 11, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-11-2013', 'PIT', 'Pittsburgh', 'Pirates', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-11-2013', 'TOR', 'Toronto', 'Blue Jays', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-11-2013', 'COL', 'Colorado', 'Rockies', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-11-2013', 'ATL', 'Atlanta', 'Braves', 'SF', 'San Francisco', 'Giants');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-11-2013', 'CHC', 'Chicago', 'Cubs', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-11-2013', 'MIL', 'Milwaukee', 'Brewers', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-11-2013', 'SD', 'San Diego', 'Padres', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-11-2013', 'CLE', 'Cleveland', 'Indians', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-11-2013', 'LAA', 'Anaheim', 'Angels', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-11-2013', 'BAL', 'Baltimore', 'Orioles', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-11-2013', 'NYY', 'New York', 'Yankees', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-11-2013', 'TEX', 'Texas', 'Rangers', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-11-2013', 'PHI', 'Philadelphia', 'Phillies', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-11-2013', 'MIA', 'Miami', 'Marlins', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-11-2013', 'OAK', 'Oakland', 'Athletics', 'SEA', 'Seattle', 'Mariners');




--May 12, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-12-2013', 'CLE', 'Cleveland', 'Indians', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-12-2013', 'MIL', 'Milwaukee', 'Brewers', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-12-2013', 'PIT', 'Pittsburgh', 'Pirates', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-12-2013', 'CHC', 'Chicago', 'Cubs', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-12-2013', 'TOR', 'Toronto', 'Blue Jays', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-12-2013', 'SD', 'San Diego', 'Padres', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-12-2013', 'BAL', 'Baltimore', 'Orioles', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-12-2013', 'NYY', 'New York', 'Yankees', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-12-2013', 'TEX', 'Texas', 'Rangers', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-12-2013', 'COL', 'Colorado', 'Rockies', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-12-2013', 'ATL', 'Atlanta', 'Braves', 'SF', 'San Francisco', 'Giants');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-12-2013', 'MIA', 'Miami', 'Marlins', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-12-2013', 'OAK', 'Oakland', 'Athletics', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-12-2013', 'PHI', 'Philadelphia', 'Phillies', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-12-2013', 'LAA', 'Anaheim', 'Angels', 'CHW', 'Chicago', 'White Sox');




--May 13, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-13-2013', 'NYY', 'New York', 'Yankees', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-13-2013', 'NYY', 'New York', 'Yankees', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-13-2013', 'MIL', 'Milwaukee', 'Brewers', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-13-2013', 'NYM', 'New York', 'Mets', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-13-2013', 'HOU', 'Houston', 'Astros', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-13-2013', 'COL', 'Colorado', 'Rockies', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-13-2013', 'CHW', 'Chicago', 'White Sox', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-13-2013', 'ATL', 'Atlanta', 'Braves', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-13-2013', 'KC', 'Kansas City', 'Royals', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-13-2013', 'TEX', 'Texas', 'Rangers', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-13-2013', 'WSH', 'Washington D.C.', 'Nationals', 'LAD', 'Los Angeles', 'Dodgers');




--May 14, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-14-2013', 'CLE', 'Cleveland', 'Indians', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-14-2013', 'MIL', 'Milwaukee', 'Brewers', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-14-2013', 'SD', 'San Diego', 'Padres', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-14-2013', 'SEA', 'Seattle', 'Mariners', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-14-2013', 'SF', 'San Francisco', 'Giants', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-14-2013', 'HOU', 'Houston', 'Astros', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-14-2013', 'BOS', 'Boston', 'Red Sox', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-14-2013', 'CIN', 'Cincinatti', 'Reds', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-14-2013', 'COL', 'Colorado', 'Rockies', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-14-2013', 'CHW', 'Chicago', 'White Sox', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-14-2013', 'NYM', 'New York', 'Mets', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-14-2013', 'ATL', 'Atlanta', 'Braves', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-14-2013', 'KC', 'Kansas City', 'Royals', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-14-2013', 'TEX', 'Texas', 'Rangers', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-14-2013', 'WSH', 'Washington D.C.', 'Nationals', 'LAD', 'Los Angeles', 'Dodgers');




--May 15, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-15-2013', 'SD', 'San Diego', 'Padres', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-15-2013', 'CLE', 'Cleveland', 'Indians', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-15-2013', 'HOU', 'Houston', 'Astros', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-15-2013', 'CHW', 'Chicago', 'White Sox', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-15-2013', 'TEX', 'Texas', 'Rangers', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-15-2013', 'ATL', 'Atlanta', 'Braves', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-15-2013', 'MIL', 'Milwaukee', 'Brewers', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-15-2013', 'SEA', 'Seattle', 'Mariners', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-15-2013', 'SF', 'San Francisco', 'Giants', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-15-2013', 'BOS', 'Boston', 'Red Sox', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-15-2013', 'CIN', 'Cincinatti', 'Reds', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-15-2013', 'COL', 'Colorado', 'Rockies', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-15-2013', 'NYM', 'New York', 'Mets', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-15-2013', 'KC', 'Kansas City', 'Royals', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-15-2013', 'WSH', 'Washington D.C.', 'Nationals', 'LAD', 'Los Angeles', 'Dodgers');




--May 16, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-16-2013 13:45:00', 'NYM', 'New York', 'Mets', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-16-2013 19:05:00', 'MIL', 'Milwaukee', 'Brewers', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-16-2013 19:05:00', 'SEA', 'Seattle', 'Mariners', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-16-2013 19:10:00', 'BOS', 'Boston', 'Red Sox', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-16-2013 19:10:00', 'CIN', 'Cincinatti', 'Reds', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-16-2013 20:05:00', 'DET', 'Detroit', 'Tigers', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-16-2013 20:40:00', 'SF', 'San Francisco', 'Giants', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-16-2013 22:05:00', 'CHW', 'Chicago', 'White Sox', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-16-2013 22:10:00', 'WSH', 'Washington D.C.', 'Nationals', 'PIT', 'Pittsburgh', 'Pirates');




--May 17, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-17-2013 14:20:00', 'NYM', 'New York', 'Mets', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-17-2013 19:05:00', 'CIN', 'Cincinatti', 'Reds', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-17-2013 19:05:00', 'HOU', 'Houston', 'Astros', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-17-2013 19:05:00', 'SEA', 'Seattle', 'Mariners', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-17-2013 19:05:00', 'TB', 'Tampa Bay', 'Rays', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-17-2013 19:05:00', 'TOR', 'Toronto', 'Blue Jays', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-17-2013 19:10:00', 'ARI', 'Arizona', 'Diamondbacks', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-17-2013 19:30:00', 'LAD', 'Los Angeles', 'Dodgers', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-17-2013 20:05:00', 'DET', 'Detroit', 'Tigers', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-17-2013 20:10:00', 'BOS', 'Boston', 'Red Sox', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-17-2013 20:15:00', 'MIL', 'Milwaukee', 'Brewers', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-17-2013 20:40:00', 'SF', 'San Francisco', 'Giants', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-17-2013 22:05:00', 'CHW', 'Chicago', 'White Sox', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-17-2013 22:05:00', 'KC', 'Kansas City', 'Royals', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-17-2013 22:10:00', 'WSH', 'Washington D.C.', 'Nationals', 'SD', 'San Diego', 'Padres');




--May 18, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-18-2013 13:05:00', 'NYM', 'New York', 'Mets', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-18-2013 13:05:00', 'SEA', 'Seattle', 'Mariners', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-18-2013 13:05:00', 'TOR', 'Toronto', 'Blue Jays', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-18-2013 16:05:00', 'CHW', 'Chicago', 'White Sox', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-18-2013 16:05:00', 'CIN', 'Cincinatti', 'Reds', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-18-2013 16:05:00', 'TB', 'Tampa Bay', 'Rays', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-18-2013 19:05:00', 'HOU', 'Houston', 'Astros', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-18-2013 19:10:00', 'ARI', 'Arizona', 'Diamondbacks', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-18-2013 19:10:00', 'BOS', 'Boston', 'Red Sox', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-18-2013 19:10:00', 'LAD', 'Los Angeles', 'Dodgers', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-18-2013 19:15:00', 'MIL', 'Milwaukee', 'Brewers', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-18-2013 20:05:00', 'DET', 'Detroit', 'Tigers', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-18-2013 20:10:00', 'SF', 'San Francisco', 'Giants', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-18-2013 20:40:00', 'WSH', 'Washington D.C.', 'Nationals', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-18-2013 21:05:00', 'KC', 'Kansas City', 'Royals', 'OAK', 'Oakland', 'Athletics');




--May 19, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-19-2013 13:05:00', 'SEA', 'Seattle', 'Mariners', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-19-2013 13:05:00', 'TOR', 'Toronto', 'Blue Jays', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-19-2013 13:10:00', 'ARI', 'Arizona', 'Diamondbacks', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-19-2013 13:35:00', 'CIN', 'Cincinatti', 'Reds', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-19-2013 13:35:00', 'HOU', 'Houston', 'Astros', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-19-2013 13:35:00', 'LAD', 'Los Angeles', 'Dodgers', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-19-2013 13:35:00', 'TB', 'Tampa Bay', 'Rays', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-19-2013 14:10:00', 'BOS', 'Boston', 'Red Sox', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-19-2013 14:15:00', 'MIL', 'Milwaukee', 'Brewers', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-19-2013 14:20:00', 'NYM', 'New York', 'Mets', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-19-2013 15:35:00', 'CHW', 'Chicago', 'White Sox', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-19-2013 16:05:00', 'KC', 'Kansas City', 'Royals', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-19-2013 16:10:00', 'SF', 'San Francisco', 'Giants', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-19-2013 16:10:00', 'WSH', 'Washington D.C.', 'Nationals', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-19-2013 20:05:00', 'DET', 'Detroit', 'Tigers', 'TEX', 'Texas', 'Rangers');




--May 20, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-20-2013 12:05:00', 'SEA', 'Seattle', 'Mariners', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-20-2013 13:07:00', 'TB', 'Tampa Bay', 'Rays', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-20-2013 19:05:00', 'NYY', 'New York', 'Yankees', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-20-2013 19:10:00', 'CIN', 'Cincinatti', 'Reds', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-20-2013 19:10:00', 'MIN', 'Minnesota', 'Twins', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-20-2013 19:10:00', 'PHI', 'Philadelphia', 'Phillies', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-20-2013 20:05:00', 'OAK', 'Oakland', 'Athletics', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-20-2013 20:10:00', 'BOS', 'Boston', 'Red Sox', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-20-2013 20:10:00', 'KC', 'Kansas City', 'Royals', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-20-2013 20:10:00', 'LAD', 'Los Angeles', 'Dodgers', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-20-2013 20:40:00', 'ARI', 'Arizona', 'Diamondbacks', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-20-2013 22:10:00', 'STL', 'St. Louis', 'Cardinals', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-20-2013 22:15:00', 'WSH', 'Washington D.C.', 'Nationals', 'SF', 'San Francisco', 'Giants');



--May 21, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-21-2013 19:05:00', 'CHC', 'Chicago', 'Cubs', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-21-2013 19:05:00', 'DET', 'Detroit', 'Tigers', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-21-2013 19:05:00', 'NYY', 'New York', 'Yankees', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-21-2013 19:07:00', 'TB', 'Tampa Bay', 'Rays', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-21-2013 19:10:00', 'CIN', 'Cincinatti', 'Reds', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-21-2013 19:10:00', 'MIN', 'Minnesota', 'Twins', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-21-2013 19:10:00', 'PHI', 'Philadelphia', 'Phillies', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-21-2013 20:05:00', 'OAK', 'Oakland', 'Athletics', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-21-2013 20:10:00', 'BOS', 'Boston', 'Red Sox', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-21-2013 20:10:00', 'KC', 'Kansas City', 'Royals', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-21-2013 20:10:00', 'LAD', 'Los Angeles', 'Dodgers', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-21-2013 20:40:00', 'ARI', 'Arizona', 'Diamondbacks', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-21-2013 22:05:00', 'SEA', 'Seattle', 'Mariners', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-21-2013 22:10:00', 'STL', 'St. Louis', 'Cardinals', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-21-2013 22:15:00', 'WSH', 'Washington D.C.', 'Nationals', 'SF', 'San Francisco', 'Giants');




--May 22, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-22-2013 12:10:00', 'MIN', 'Minnesota', 'Twins', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-22-2013 13:10:00', 'CIN', 'Cincinatti', 'Reds', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-22-2013 13:10:00', 'LAD', 'Los Angeles', 'Dodgers', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-22-2013 14:05:00', 'OAK', 'Oakland', 'Athletics', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-22-2013 15:10:00', 'ARI', 'Arizona', 'Diamondbacks', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-22-2013 15:45:00', 'WSH', 'Washington D.C.', 'Nationals', 'SF', 'San Francisco', 'Giants');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-22-2013 16:37:00', 'TB', 'Tampa Bay', 'Rays', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-22-2013 19:05:00', 'CHC', 'Chicago', 'Cubs', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-22-2013 19:05:00', 'DET', 'Detroit', 'Tigers', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-22-2013 19:05:00', 'NYY', 'New York', 'Yankees', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-22-2013 19:05:00', 'SEA', 'Seattle', 'Mariners', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-22-2013 19:10:00', 'PHI', 'Philadelphia', 'Phillies', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-22-2013 20:10:00', 'BOS', 'Boston', 'Red Sox', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-22-2013 20:10:00', 'KC', 'Kansas City', 'Royals', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-22-2013 22:10:00', 'STL', 'St. Louis', 'Cardinals', 'SD', 'San Diego', 'Padres');




--May 23, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-23-2013 12:35:00', 'CHC', 'Chicago', 'Cubs', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-23-2013 19:07:00', 'BAL', 'Baltimore', 'Orioles', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-23-2013 19:08:00', 'MIN', 'Minnesota', 'Twins', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-23-2013 19:10:00', 'CLE', 'Cleveland', 'Indians', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-23-2013 20:10:00', 'LAA', 'Anaheim', 'Angels', 'KC', 'Kansas City', 'Royals');




--May 24, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-24-2013 19:05:00', 'PHI', 'Philadelphia', 'Phillies', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-24-2013 19:07:00', 'BAL', 'Baltimore', 'Orioles', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-24-2013 19:08:00', 'MIN', 'Minnesota', 'Twins', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-24-2013 19:10:00', 'ATL', 'Atlanta', 'Braves', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-24-2013 19:10:00', 'CHC', 'Chicago', 'Cubs', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-24-2013 19:10:00', 'CLE', 'Cleveland', 'Indians', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-24-2013 19:10:00', 'NYY', 'New York', 'Yankees', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-24-2013 20:10:00', 'LAA', 'Anaheim', 'Angels', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-24-2013 20:10:00', 'MIA', 'Miami', 'Marlins', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-24-2013 20:10:00', 'OAK', 'Oakland', 'Athletics', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-24-2013 20:10:00', 'PIT', 'Pittsburgh', 'Pirates', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-24-2013 21:40:00', 'SD', 'San Diego', 'Padres', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-24-2013 22:10:00', 'STL', 'St. Louis', 'Cardinals', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-24-2013 22:10:00', 'TEX', 'Texas', 'Rangers', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-24-2013 22:15:00', 'COL', 'Colorado', 'Rockies', 'SF', 'San Francisco', 'Giants');




--May 25, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-25-2013 13:07:00', 'BAL', 'Baltimore', 'Orioles', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-25-2013 13:35:00', 'CLE', 'Cleveland', 'Indians', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-25-2013 14:10:00', 'LAA', 'Anaheim', 'Angels', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-25-2013 16:05:00', 'COL', 'Colorado', 'Rockies', 'SF', 'San Francisco', 'Giants');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-25-2013 16:08:00', 'MIN', 'Minnesota', 'Twins', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-25-2013 16:10:00', 'CHC', 'Chicago', 'Cubs', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-25-2013 16:10:00', 'NYY', 'New York', 'Yankees', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-25-2013 16:10:00', 'PIT', 'Pittsburgh', 'Pirates', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-25-2013 19:15:00', 'ATL', 'Atlanta', 'Braves', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-25-2013 19:15:00', 'MIA', 'Miami', 'Marlins', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-25-2013 19:15:00', 'OAK', 'Oakland', 'Athletics', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-25-2013 19:15:00', 'PHI', 'Philadelphia', 'Phillies', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-25-2013 19:15:00', 'STL', 'St. Louis', 'Cardinals', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-25-2013 22:10:00', 'SD', 'San Diego', 'Padres', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-25-2013 22:10:00', 'TEX', 'Texas', 'Rangers', 'SEA', 'Seattle', 'Mariners');




--May 26, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-26-2013 13:07:00', 'BAL', 'Baltimore', 'Orioles', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-26-2013', 'MIN', 'Minnesota', 'Twins', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-26-2013 13:10:00', 'CHC', 'Chicago', 'Cubs', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-26-2013', 'CLE', 'Cleveland', 'Indians', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-26-2013', 'PHI', 'Philadelphia', 'Phillies', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-26-2013', 'NYY', 'New York', 'Yankees', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-26-2013', 'LAA', 'Anaheim', 'Angels', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-26-2013', 'MIA', 'Miami', 'Marlins', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-26-2013', 'OAK', 'Oakland', 'Athletics', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-26-2013', 'PIT', 'Pittsburgh', 'Pirates', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-26-2013 16:05:00', 'COL', 'Colorado', 'Rockies', 'SF', 'San Francisco', 'Giants');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-26-2013', 'SD', 'San Diego', 'Padres', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-26-2013', 'STL', 'St. Louis', 'Cardinals', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-26-2013', 'TEX', 'Texas', 'Rangers', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-26-2013 20:05:00', 'ATL', 'Atlanta', 'Braves', 'NYM', 'New York', 'Mets');




--May 27, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-27-2013 13:05:00', 'BAL', 'Baltimore', 'Orioles', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-27-2013 13:08:00', 'PIT', 'Pittsburgh', 'Pirates', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-27-2013 13:10:00', 'CLE', 'Cleveland', 'Indians', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-27-2013 14:10:00', 'COL', 'Colorado', 'Rockies', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-27-2013 14:10:00', 'MIN', 'Minnesota', 'Twins', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-27-2013 14:10:00', 'STL', 'St. Louis', 'Cardinals', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-27-2013 15:10:00', 'MIA', 'Miami', 'Marlins', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-27-2013 15:40:00', 'TEX', 'Texas', 'Rangers', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-27-2013 16:05:00', 'SF', 'San Francisco', 'Giants', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-27-2013 16:10:00', 'SD', 'San Diego', 'Padres', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-27-2013 19:07:00', 'ATL', 'Atlanta', 'Braves', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-27-2013 19:10:00', 'CHC', 'Chicago', 'Cubs', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-27-2013 19:10:00', 'NYY', 'New York', 'Yankees', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-27-2013 19:10:00', 'PHI', 'Philadelphia', 'Phillies', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-27-2013 20:10:00', 'LAA', 'Anaheim', 'Angels', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-27-2013 21:40:00', 'TEX', 'Texas', 'Rangers', 'ARI', 'Arizona', 'Diamondbacks');





--May 28, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-28-2013 12:37:00', 'ATL', 'Atlanta', 'Braves', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-28-2013 14:10:00', 'COL', 'Colorado', 'Rockies', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-28-2013 19:05:00', 'BAL', 'Baltimore', 'Orioles', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-28-2013 19:08:00', 'PIT', 'Pittsburgh', 'Pirates', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-28-2013 19:10:00', 'CLE', 'Cleveland', 'Indians', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-28-2013 19:10:00', 'MIA', 'Miami', 'Marlins', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-28-2013 19:10:00', 'NYY', 'New York', 'Yankees', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-28-2013 19:10:00', 'PHI', 'Philadelphia', 'Phillies', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-28-2013 20:10:00', 'CHC', 'Chicago', 'Cubs', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-28-2013 20:10:00', 'MIN', 'Minnesota', 'Twins', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-28-2013 20:10:00', 'STL', 'St. Louis', 'Cardinals', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-28-2013 22:05:00', 'SF', 'San Francisco', 'Giants', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-28-2013 22:10:00', 'LAA', '', 'Angels', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-28-2013 22:10:00', 'SD', 'San Diego', 'Padres', 'SEA', 'Seattle', 'Mariners');




--May 29, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-29-2013 14:20:00', 'CHW', 'Chicago', 'White Sox', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-29-2013 19:05:00', 'BOS', 'Boston', 'Red Sox', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-29-2013 19:05:00', 'CIN', 'Cincinatti', 'Reds', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-29-2013 19:05:00', 'DET', 'Detroit', 'Tigers', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-29-2013 19:05:00', 'NYM', 'New York', 'Mets', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-29-2013 19:05:00', 'WSH', 'Washington D.C.', 'Nationals', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-29-2013 19:10:00', 'TB', 'Tampa Bay', 'Rays', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-29-2013 19:10:00', 'TOR', 'Toronto', 'Blue Jays', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-29-2013 20:05:00', 'ARI', 'Arizona', 'Diamondbacks', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-29-2013 20:10:00', 'MIL', 'Milwaukee', 'Brewers', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-29-2013 20:15:00', 'KC', 'Kansas City', 'Royals', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-29-2013 20:40:00', 'HOU', 'Houston', 'Astros', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-29-2013 22:05:00', 'LAD', 'Los Angeles', 'Dodgers', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-29-2013 22:10:00', 'SEA', 'Seattle', 'Mariners', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-29-2013 22:15:00', 'OAK', 'Oakland', 'Athletics', 'SF', 'San Francisco', 'Giants');




--May 30, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-30-2013 14:05:00', 'ARI', 'Arizona', 'Diamondbacks', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-30-2013 14:20:00', 'CHW', 'Chicago', 'White Sox', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-30-2013 15:40:00', 'SEA', 'Seattle', 'Mariners', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-30-2013 15:45:00', 'OAK', 'Oakland', 'Athletics', 'SF', 'San Francisco', 'Giants');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-30-2013 19:05:00', 'BOS', 'Boston', 'Red Sox', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-30-2013 19:05:00', 'CIN', 'Cincinatti', 'Reds', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-30-2013 19:05:00', 'DET', 'Detroit', 'Tigers', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-30-2013 19:05:00', 'NYM', 'New York', 'Mets', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-30-2013 19:05:00', 'WSH', 'Washington D.C.', 'Nationals', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-30-2013 19:10:00', 'TB', 'Tampa Bay', 'Rays', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-30-2013 19:10:00', 'TOR', 'Toronto', 'Blue Jays', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-30-2013 20:10:00', 'MIL', 'Milwaukee', 'Brewers', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-30-2013 20:15:00', 'KC', 'Kansas City', 'Royals', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-30-2013 20:40:00', 'HOU', 'Houston', 'Astros', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-30-2013 22:05:00', 'LAD', 'Los Angeles', 'Dodgers', 'LAA', 'Anaheim', 'Angels');




--May 31, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-31-2013 14:20:00', 'ARI', 'Arizona', 'Diamondbacks', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-31-2013 19:05:00', 'BOS', 'Boston', 'Red Sox', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-31-2013 19:05:00', 'CIN', 'Cincinatti', 'Reds', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-31-2013 19:05:00', 'DET', 'Detroit', 'Tigers', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-31-2013 19:05:00', 'MIL', 'Milwaukee', 'Brewers', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-31-2013 19:05:00', 'TB', 'Tampa Bay', 'Rays', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-31-2013 19:10:00', 'NYM', 'New York', 'Mets', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-31-2013 19:30:00', 'WSH', 'Washington D.C.', 'Nationals', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-31-2013 20:05:00', 'KC', 'Kansas City', 'Royals', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-31-2013 20:10:00', 'SEA', 'Seattle', 'Mariners', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-31-2013 20:15:00', 'SF', 'San Francisco', 'Giants', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-31-2013 20:40:00', 'LAD', 'Los Angeles', 'Dodgers', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-31-2013 22:05:00', 'CHW', 'Chicago', 'White Sox', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-31-2013 22:05:00', 'HOU', 'Houston', 'Astros', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '5-31-2013 22:10:00', 'TOR', 'Toronto', 'Blue Jays', 'SD', 'San Diego', 'Padres');
