--July 1, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-1-2013 13:07:00', 'DET', 'Detroit', 'Tigers', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-1-2013 19:05:00', 'MIL', 'Milwaukee', 'Brewers', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-1-2013 19:10:00', 'ARI', 'Arizona', 'Diamondbacks', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-1-2013 19:10:00', 'SD', 'San Diego', 'Padres', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-1-2013 19:10:00', 'SF', 'San Francisco', 'Giants', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-1-2013 20:10:00', 'NYY', 'New York', 'Yankees', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-1-2013 20:10:00', 'TB', 'Tampa Bay', 'Rays', 'HOU', 'Houston', 'Astros');





--July 2, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-2-2013 19:05:00', 'MIL', 'Milwaukee', 'Brewers', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-2-2013 19:05:00', 'PHI', 'Philadelphia', 'Phillies', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-2-2013 19:07:00', 'DET', 'Detroit', 'Tigers', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-2-2013 19:10:00', 'ARI', 'Arizona', 'Diamondbacks', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-2-2013 19:10:00', 'MIA', 'Miami', 'Marlins', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-2-2013 19:10:00', 'SD', 'San Diego', 'Padres', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-2-2013 19:10:00', 'SF', 'San Francisco', 'Giants', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-2-2013 20:05:00', 'SEA', 'Seattle', 'Mariners', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-2-2013 20:10:00', 'BAL', 'Baltimore', 'Orioles', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-2-2013 20:10:00', 'CLE', 'Cleveland', 'Indians', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-2-2013 20:10:00', 'NYY', 'New York', 'Yankees', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-2-2013 20:10:00', 'TB', 'Tampa Bay', 'Rays', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-2-2013 20:40:00', 'LAD', 'Los Angeles', 'Dodgers', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-2-2013 22:05:00', 'CHC', 'Chicago', 'Cubs', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-2-2013 22:05:00', 'STL', 'St. Louis', 'Cardinals', 'LAA', 'Anaheim', 'Angels');





--July 3, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-3-2013 18:05:00', 'MIL', 'Milwaukee', 'Brewers', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-3-2013 19:05:00', 'PHI', 'Philadelphia', 'Phillies', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-3-2013 19:07:00', 'DET', 'Detroit', 'Tigers', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-3-2013 19:10:00', 'ARI', 'Arizona', 'Diamondbacks', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-3-2013 19:10:00', 'BAL', 'Baltimore', 'Orioles', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-3-2013 19:10:00', 'MIA', 'Miami', 'Marlins', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-3-2013 19:10:00', 'SD', 'San Diego', 'Padres', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-3-2013 19:10:00', 'SF', 'San Francisco', 'Giants', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-3-2013 20:05:00', 'SEA', 'Seattle', 'Mariners', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-3-2013 20:10:00', 'CLE', 'Cleveland', 'Indians', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-3-2013 20:10:00', 'LAD', 'Los Angeles', 'Dodgers', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-3-2013 20:10:00', 'NYY', 'New York', 'Yankees', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-3-2013 20:10:00', 'TB', 'Tampa Bay', 'Rays', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-3-2013 22:05:00', 'CHC', 'Chicago', 'Cubs', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-3-2013 22:05:00', 'STL', 'St. Louis', 'Cardinals', 'LAA', 'Anaheim', 'Angels');





--July 4, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-4-2013 11:05:00', 'MIL', 'Milwaukee', 'Brewers', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-4-2013 13:10:00', 'ARI', 'Arizona', 'Diamondbacks', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-4-2013 13:10:00', 'SF', 'San Francisco', 'Giants', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-4-2013 13:35:00', 'PHI', 'Philadelphia', 'Phillies', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-4-2013 13:35:00', 'SD', 'San Diego', 'Padres', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-4-2013 14:10:00', 'BAL', 'Baltimore', 'Orioles', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-4-2013 14:10:00', 'CLE', 'Cleveland', 'Indians', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-4-2013 14:10:00', 'NYY', 'New York', 'Yankees', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-4-2013 14:10:00', 'TB', 'Tampa Bay', 'Rays', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-4-2013 16:05:00', 'CHC', 'Chicago', 'Cubs', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-4-2013 19:07:00', 'DET', 'Detroit', 'Tigers', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-4-2013 19:10:00', 'MIA', 'Miami', 'Marlins', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-4-2013 20:05:00', 'SEA', 'Seattle', 'Mariners', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-4-2013 20:10:00', 'LAD', 'Los Angeles', 'Dodgers', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-4-2013 21:05:00', 'STL', 'St. Louis', 'Cardinals', 'LAA', 'Anaheim', 'Angels');





--July 5, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-5-2013 00:00:00', 'PIT', 'Pittsburgh', 'Pirates', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-5-2013 19:05:00', 'ATL', 'Atlanta', 'Braves', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-5-2013 19:05:00', 'BAL', 'Baltimore', 'Orioles', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-5-2013 19:05:00', 'DET', 'Detroit', 'Tigers', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-5-2013 19:05:00', 'SD', 'San Diego', 'Padres', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-5-2013 19:07:00', 'MIN', 'Minnesota', 'Twins', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-5-2013 19:10:00', 'CHW', 'Chicago', 'White Sox', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-5-2013 19:10:00', 'SEA', 'Seattle', 'Mariners', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-5-2013 20:05:00', 'HOU', 'Houston', 'Astros', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-5-2013 20:10:00', 'NYM', 'New York', 'Mets', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-5-2013 20:10:00', 'OAK', 'Oakland', 'Athletics', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-5-2013 20:15:00', 'MIA', 'Miami', 'Marlins', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-5-2013 21:40:00', 'COL', 'Colorado', 'Rockies', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-5-2013 22:05:00', 'BOS', 'Boston', 'Red Sox', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-5-2013 22:15:00', 'LAD', 'Los Angeles', 'Dodgers', 'SF', 'San Francisco', 'Giants');





--July 6, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-6-2013 13:05:00', 'BAL', 'Baltimore', 'Orioles', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-6-2013 13:07:00', 'MIN', 'Minnesota', 'Twins', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-6-2013 14:10:00', 'OAK', 'Oakland', 'Athletics', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-6-2013 14:15:00', 'MIA', 'Miami', 'Marlins', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-6-2013 16:05:00', 'DET', 'Detroit', 'Tigers', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-6-2013 16:05:00', 'PIT', 'Pittsburgh', 'Pirates', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-6-2013 16:05:00', 'SD', 'San Diego', 'Padres', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-6-2013 16:10:00', 'SEA', 'Seattle', 'Mariners', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-6-2013 19:15:00', 'ATL', 'Atlanta', 'Braves', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-6-2013 19:15:00', 'CHW', 'Chicago', 'White Sox', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-6-2013 19:15:00', 'HOU', 'Houston', 'Astros', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-6-2013 19:15:00', 'LAD', 'Los Angeles', 'Dodgers', 'SF', 'San Francisco', 'Giants');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-6-2013 19:15:00', 'NYM', 'New York', 'Mets', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-6-2013 22:05:00', 'BOS', 'Boston', 'Red Sox', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-6-2013 22:10:00', 'COL', 'Colorado', 'Rockies', 'ARI', 'Arizona', 'Diamondbacks');





--July 7, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-7-2013 00:00:00', 'BOS', 'Boston', 'Red Sox', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-7-2013 13:05:00', 'BAL', 'Baltimore', 'Orioles', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-7-2013 13:05:00', 'DET', 'Detroit', 'Tigers', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-7-2013 13:07:00', 'MIN', 'Minnesota', 'Twins', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-7-2013 13:10:00', 'SEA', 'Seattle', 'Mariners', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-7-2013 13:35:00', 'ATL', 'Atlanta', 'Braves', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-7-2013 13:35:00', 'SD', 'San Diego', 'Padres', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-7-2013 13:40:00', 'CHW', 'Chicago', 'White Sox', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-7-2013 14:10:00', 'NYM', 'New York', 'Mets', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-7-2013 14:10:00', 'OAK', 'Oakland', 'Athletics', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-7-2013 14:15:00', 'MIA', 'Miami', 'Marlins', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-7-2013 14:20:00', 'PIT', 'Pittsburgh', 'Pirates', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-7-2013 15:05:00', 'HOU', 'Houston', 'Astros', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-7-2013 16:05:00', 'LAD', 'Los Angeles', 'Dodgers', 'SF', 'San Francisco', 'Giants');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-7-2013 16:10:00', 'COL', 'Colorado', 'Rockies', 'ARI', 'Arizona', 'Diamondbacks');





--July 8, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-8-2013 19:05:00', 'DET', 'Detroit', 'Tigers', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-8-2013 19:05:00', 'KC', 'Kansas City', 'Royals', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-8-2013 19:05:00', 'OAK', 'Oakland', 'Athletics', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-8-2013 19:05:00', 'TEX', 'Texas', 'Rangers', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-8-2013 19:05:00', 'WSH', 'Washington D.C.', 'Nationals', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-8-2013 19:10:00', 'ATL', 'Atlanta', 'Braves', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-8-2013 19:10:00', 'MIN', 'Minnesota', 'Twins', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-8-2013 20:10:00', 'CIN', 'Cincinatti', 'Reds', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-8-2013 21:40:00', 'LAD', 'Los Angeles', 'Dodgers', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-8-2013 22:10:00', 'BOS', 'Boston', 'Red Sox', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-8-2013 22:10:00', 'COL', 'Colorado', 'Rockies', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-8-2013 22:15:00', 'NYM', 'New York', 'Mets', 'SF', 'San Francisco', 'Giants');





--July 9, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-9-2013 19:05:00', 'KC', 'Kansas City', 'Royals', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-9-2013 19:05:00', 'OAK', 'Oakland', 'Athletics', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-9-2013 19:05:00', 'TEX', 'Texas', 'Rangers', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-9-2013 19:05:00', 'TOR', 'Toronto', 'Blue Jays', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-9-2013 19:05:00', 'WSH', 'Washington D.C.', 'Nationals', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-9-2013 19:08:00', 'CHW', 'Chicago', 'White Sox', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-9-2013 19:10:00', 'ATL', 'Atlanta', 'Braves', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-9-2013 19:10:00', 'MIN', 'Minnesota', 'Twins', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-9-2013 20:05:00', 'LAA', 'Anaheim', 'Angels', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-9-2013 20:10:00', 'CIN', 'Cincinatti', 'Reds', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-9-2013 20:15:00', 'HOU', 'Houston', 'Astros', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-9-2013 21:40:00', 'LAD', 'Los Angeles', 'Dodgers', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-9-2013 22:10:00', 'BOS', 'Boston', 'Red Sox', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-9-2013 22:10:00', 'COL', 'Colorado', 'Rockies', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-9-2013 22:15:00', 'NYM', 'New York', 'Mets', 'SF', 'San Francisco', 'Giants');





--July 10, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-10-2013 12:40:00', 'ATL', 'Atlanta', 'Braves', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-10-2013 14:10:00', 'CIN', 'Cincinatti', 'Reds', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-10-2013 15:45:00', 'NYM', 'New York', 'Mets', 'SF', 'San Francisco', 'Giants');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-10-2013 19:05:00', 'KC', 'Kansas City', 'Royals', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-10-2013 19:05:00', 'OAK', 'Oakland', 'Athletics', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-10-2013 19:05:00', 'TEX', 'Texas', 'Rangers', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-10-2013 19:05:00', 'TOR', 'Toronto', 'Blue Jays', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-10-2013 19:05:00', 'WSH', 'Washington D.C.', 'Nationals', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-10-2013 19:08:00', 'CHW', 'Chicago', 'White Sox', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-10-2013 19:10:00', 'MIN', 'Minnesota', 'Twins', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-10-2013 20:05:00', 'LAA', 'Anaheim', 'Angels', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-10-2013 20:15:00', 'HOU', 'Houston', 'Astros', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-10-2013 21:40:00', 'LAD', 'Los Angeles', 'Dodgers', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-10-2013 22:10:00', 'BOS', 'Boston', 'Red Sox', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-10-2013 22:10:00', 'COL', 'Colorado', 'Rockies', 'SD', 'San Diego', 'Padres');





--July 11, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-11-2013 12:05:00', 'TOR', 'Toronto', 'Blue Jays', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-11-2013 12:10:00', 'MIN', 'Minnesota', 'Twins', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-11-2013 13:05:00', 'KC', 'Kansas City', 'Royals', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-11-2013 13:08:00', 'CHW', 'Chicago', 'White Sox', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-11-2013 15:40:00', 'BOS', 'Boston', 'Red Sox', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-11-2013 19:05:00', 'TEX', 'Texas', 'Rangers', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-11-2013 19:05:00', 'WSH', 'Washington D.C.', 'Nationals', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-11-2013 19:10:00', 'CIN', 'Cincinatti', 'Reds', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-11-2013 20:05:00', 'STL', 'St. Louis', 'Cardinals', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-11-2013 21:40:00', 'MIL', 'Milwaukee', 'Brewers', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-11-2013 22:10:00', 'COL', 'Colorado', 'Rockies', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-11-2013 22:10:00', 'SF', 'San Francisco', 'Giants', 'SD', 'San Diego', 'Padres');





--July 12, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-12-2013 19:05:00', 'STL', 'St. Louis', 'Cardinals', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-12-2013 19:05:00', 'CHW', 'Chicago', 'White Sox', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-12-2013 19:05:00', 'KC', 'Kansas City', 'Royals', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-12-2013 19:05:00', 'MIN', 'Minnesota', 'Twins', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-12-2013 19:05:00', 'NYM', 'New York', 'Mets', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-12-2013 19:05:00', 'TOR', 'Toronto', 'Blue Jays', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-12-2013 19:08:00', 'TEX', 'Texas', 'Rangers', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-12-2013 19:10:00', 'HOU', 'Houston', 'Astros', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-12-2013 19:10:00', 'WSH', 'Washington D.C.', 'Nationals', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-12-2013 19:30:00', 'CIN', 'Cincinatti', 'Reds', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-12-2013 21:40:00', 'MIL', 'Milwaukee', 'Brewers', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-12-2013 22:05:00', 'BOS', 'Boston', 'Red Sox', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-12-2013 22:10:00', 'LAA', 'Anaheim', 'Angels', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-12-2013 22:10:00', 'COL', 'Colorado', 'Rockies', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-12-2013 22:10:00', 'SF', 'San Francisco', 'Giants', 'SD', 'San Diego', 'Padres');





--July 13, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-13-2013 13:05:00', 'MIN', 'Minnesota', 'Twins', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-13-2013 16:05:00', 'CHW', 'Chicago', 'White Sox', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-13-2013 16:05:00', 'CIN', 'Cincinatti', 'Reds', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-13-2013 16:05:00', 'TOR', 'Toronto', 'Blue Jays', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-13-2013 16:10:00', 'HOU', 'Houston', 'Astros', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-13-2013 19:05:00', 'KC', 'Kansas City', 'Royals', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-13-2013 19:15:00', 'COL', 'Colorado', 'Rockies', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-13-2013 19:15:00', 'NYM', 'New York', 'Mets', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-13-2013 19:15:00', 'STL', 'St. Louis', 'Cardinals', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-13-2013 19:15:00', 'TEX', 'Texas', 'Rangers', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-13-2013 19:15:00', 'WSH', 'Washington D.C.', 'Nationals', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-13-2013 22:05:00', 'BOS', 'Boston', 'Red Sox', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-13-2013 22:10:00', 'LAA', 'Anaheim', 'Angels', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-13-2013 22:10:00', 'MIL', 'Milwaukee', 'Brewers', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-13-2013 22:10:00', 'SF', 'San Francisco', 'Giants', 'SD', 'San Diego', 'Padres');





--July 14, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-14-2013 13:05:00', 'KC', 'Kansas City', 'Royals', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-14-2013 13:05:00', 'MIN', 'Minnesota', 'Twins', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-14-2013 13:08:00', 'TEX', 'Texas', 'Rangers', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-14-2013 13:10:00', 'WSH', 'Washington D.C.', 'Nationals', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-14-2013 13:35:00', 'CHW', 'Chicago', 'White Sox', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-14-2013 13:35:00', 'CIN', 'Cincinatti', 'Reds', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-14-2013 13:35:00', 'NYM', 'New York', 'Mets', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-14-2013 13:35:00', 'TOR', 'Toronto', 'Blue Jays', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-14-2013 13:40:00', 'HOU', 'Houston', 'Astros', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-14-2013 16:05:00', 'BOS', 'Boston', 'Red Sox', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-14-2013 16:10:00', 'LAA', 'Anaheim', 'Angels', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-14-2013 16:10:00', 'COL', 'Colorado', 'Rockies', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-14-2013 16:10:00', 'MIL', 'Milwaukee', 'Brewers', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-14-2013 16:10:00', 'SF', 'San Francisco', 'Giants', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-14-2013 20:05:00', 'STL', 'St. Louis', 'Cardinals', 'CHC', 'Chicago', 'Cubs');





--July 15, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-15-2013', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-15-2013', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-15-2013', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-15-2013', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-15-2013', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-15-2013', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-15-2013', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-15-2013', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-15-2013', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-15-2013', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-15-2013', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-15-2013', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-15-2013', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-15-2013', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-15-2013', '', '', '', '', '', '');





--July 16, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-16-2013 00:00:00', 'AMR', 'None', 'American League All Stars', 'NAT', 'New York', 'National League All Stars');





--July 17, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');





--July 18, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');





--July 19, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-19-2013 19:05:00', 'LAD', 'Los Angeles', 'Dodgers', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-19-2013 19:07:00', 'TB', 'Tampa Bay', 'Rays', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-19-2013 19:10:00', 'NYY', 'New York', 'Yankees', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-19-2013 19:10:00', 'PHI', 'Philadelphia', 'Phillies', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-19-2013 19:10:00', 'PIT', 'Pittsburgh', 'Pirates', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-19-2013 20:05:00', 'BAL', 'Baltimore', 'Orioles', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-19-2013 20:10:00', 'ATL', 'Atlanta', 'Braves', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-19-2013 20:10:00', 'CLE', 'Cleveland', 'Indians', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-19-2013 20:10:00', 'DET', 'Detroit', 'Tigers', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-19-2013 20:10:00', 'MIA', 'Miami', 'Marlins', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-19-2013 20:10:00', 'SEA', 'Seattle', 'Mariners', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-19-2013 20:15:00', 'SD', 'San Diego', 'Padres', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-19-2013 20:40:00', 'CHC', 'Chicago', 'Cubs', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-19-2013 22:05:00', 'OAK', 'Oakland', 'Athletics', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-19-2013 22:15:00', 'ARI', 'Arizona', 'Diamondbacks', 'SF', 'San Francisco', 'Giants');





--July 20, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-20-2013 13:07:00', 'TB', 'Tampa Bay', 'Rays', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-20-2013 13:10:00', 'PHI', 'Philadelphia', 'Phillies', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-20-2013 16:05:00', 'ATL', 'Atlanta', 'Braves', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-20-2013 16:05:00', 'NYY', 'New York', 'Yankees', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-20-2013 16:05:00', 'PIT', 'Pittsburgh', 'Pirates', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-20-2013 19:05:00', 'LAD', 'Los Angeles', 'Dodgers', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-20-2013 19:10:00', 'CLE', 'Cleveland', 'Indians', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-20-2013 19:10:00', 'DET', 'Detroit', 'Tigers', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-20-2013 19:10:00', 'MIA', 'Miami', 'Marlins', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-20-2013 19:10:00', 'SEA', 'Seattle', 'Mariners', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-20-2013 19:15:00', 'SD', 'San Diego', 'Padres', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-20-2013 20:05:00', 'BAL', 'Baltimore', 'Orioles', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-20-2013 20:05:00', 'BAL', 'Baltimore', 'Orioles', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-20-2013 20:10:00', 'CHC', 'Chicago', 'Cubs', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-20-2013 21:05:00', 'ARI', 'Arizona', 'Diamondbacks', 'SF', 'San Francisco', 'Giants');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-20-2013 21:05:00', 'OAK', 'Oakland', 'Athletics', 'LAA', 'Anaheim', 'Angels');





--July 21, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-21-2013 13:07:00', 'TB', 'Tampa Bay', 'Rays', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-21-2013 13:10:00', 'PHI', 'Philadelphia', 'Phillies', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-21-2013 13:10:00', 'PIT', 'Pittsburgh', 'Pirates', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-21-2013 13:35:00', 'LAD', 'Los Angeles', 'Dodgers', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-21-2013 14:10:00', 'ATL', 'Atlanta', 'Braves', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-21-2013 14:10:00', 'CLE', 'Cleveland', 'Indians', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-21-2013 14:10:00', 'DET', 'Detroit', 'Tigers', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-21-2013 14:10:00', 'MIA', 'Miami', 'Marlins', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-21-2013 14:10:00', 'SEA', 'Seattle', 'Mariners', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-21-2013 14:15:00', 'SD', 'San Diego', 'Padres', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-21-2013 15:35:00', 'OAK', 'Oakland', 'Athletics', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-21-2013 16:05:00', 'ARI', 'Arizona', 'Diamondbacks', 'SF', 'San Francisco', 'Giants');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-21-2013 16:10:00', 'CHC', 'Chicago', 'Cubs', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-21-2013 19:05:00', 'BAL', 'Baltimore', 'Orioles', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-21-2013 20:05:00', 'NYY', 'New York', 'Yankees', 'BOS', 'Boston', 'Red Sox');





--July 22, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-22-2013 19:05:00', 'PIT', 'Pittsburgh', 'Pirates', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-22-2013 19:07:00', 'LAD', 'Los Angeles', 'Dodgers', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-22-2013 19:10:00', 'ATL', 'Atlanta', 'Braves', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-22-2013 19:10:00', 'TB', 'Tampa Bay', 'Rays', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-22-2013 20:05:00', 'NYY', 'New York', 'Yankees', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-22-2013 20:10:00', 'BAL', 'Baltimore', 'Orioles', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-22-2013 20:10:00', 'DET', 'Detroit', 'Tigers', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-22-2013 20:10:00', 'OAK', 'Oakland', 'Athletics', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-22-2013 20:10:00', 'SD', 'San Diego', 'Padres', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-22-2013 20:40:00', 'MIA', 'Miami', 'Marlins', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-22-2013 21:40:00', 'CHC', 'Chicago', 'Cubs', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-22-2013 22:05:00', 'MIN', 'Minnesota', 'Twins', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-22-2013 22:10:00', 'CLE', 'Cleveland', 'Indians', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-22-2013 22:15:00', 'CIN', 'Cincinatti', 'Reds', 'SF', 'San Francisco', 'Giants');






--July 23, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-23-2013 19:05:00', 'PIT', 'Pittsburgh', 'Pirates', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-23-2013 19:07:00', 'LAD', 'Los Angeles', 'Dodgers', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-23-2013 19:10:00', 'ATL', 'Atlanta', 'Braves', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-23-2013 19:10:00', 'TB', 'Tampa Bay', 'Rays', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-23-2013 20:05:00', 'NYY', 'New York', 'Yankees', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-23-2013 20:10:00', 'BAL', 'Baltimore', 'Orioles', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-23-2013 20:10:00', 'DET', 'Detroit', 'Tigers', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-23-2013 20:10:00', 'OAK', 'Oakland', 'Athletics', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-23-2013 20:10:00', 'SD', 'San Diego', 'Padres', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-23-2013 20:15:00', 'PHI', 'Philadelphia', 'Phillies', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-23-2013 20:40:00', 'MIA', 'Miami', 'Marlins', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-23-2013 21:40:00', 'CHC', 'Chicago', 'Cubs', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-23-2013 22:05:00', 'MIN', 'Minnesota', 'Twins', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-23-2013 22:10:00', 'CLE', 'Cleveland', 'Indians', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-23-2013 22:15:00', 'CIN', 'Cincinatti', 'Reds', 'SF', 'San Francisco', 'Giants');





--July 24, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-24-2013 14:10:00', 'OAK', 'Oakland', 'Athletics', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-24-2013 15:35:00', 'MIN', 'Minnesota', 'Twins', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-24-2013 15:40:00', 'CLE', 'Cleveland', 'Indians', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-24-2013 19:05:00', 'PIT', 'Pittsburgh', 'Pirates', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-24-2013 19:07:00', 'LAD', 'Los Angeles', 'Dodgers', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-24-2013 19:10:00', 'ATL', 'Atlanta', 'Braves', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-24-2013 19:10:00', 'TB', 'Tampa Bay', 'Rays', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-24-2013 20:05:00', 'NYY', 'New York', 'Yankees', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-24-2013 20:10:00', 'BAL', 'Baltimore', 'Orioles', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-24-2013 20:10:00', 'DET', 'Detroit', 'Tigers', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-24-2013 20:10:00', 'SD', 'San Diego', 'Padres', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-24-2013 20:15:00', 'PHI', 'Philadelphia', 'Phillies', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-24-2013 20:40:00', 'MIA', 'Miami', 'Marlins', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-24-2013 21:40:00', 'CHC', 'Chicago', 'Cubs', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-24-2013 22:15:00', 'CIN', 'Cincinatti', 'Reds', 'SF', 'San Francisco', 'Giants');





--July 25, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-25-2013 12:10:00', 'ATL', 'Atlanta', 'Braves', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-25-2013 12:35:00', 'PIT', 'Pittsburgh', 'Pirates', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-25-2013 14:05:00', 'NYY', 'New York', 'Yankees', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-25-2013 14:10:00', 'DET', 'Detroit', 'Tigers', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-25-2013 14:10:00', 'SD', 'San Diego', 'Padres', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-25-2013 15:10:00', 'MIA', 'Miami', 'Marlins', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-25-2013 19:07:00', 'HOU', 'Houston', 'Astros', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-25-2013 19:10:00', 'TB', 'Tampa Bay', 'Rays', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-25-2013 19:15:00', 'PHI', 'Philadelphia', 'Phillies', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-25-2013 20:10:00', 'BAL', 'Baltimore', 'Orioles', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-25-2013 21:40:00', 'CHC', 'Chicago', 'Cubs', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-25-2013 22:05:00', 'LAA', 'Anaheim', 'Angels', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-25-2013 22:10:00', 'CIN', 'Cincinatti', 'Reds', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-25-2013 22:10:00', 'MIN', 'Minnesota', 'Twins', 'SEA', 'Seattle', 'Mariners');






--July 26, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-26-2013 19:05:00', 'BOS', 'Boston', 'Red Sox', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-26-2013 19:05:00', 'NYM', 'New York', 'Mets', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-26-2013 19:05:00', 'TB', 'Tampa Bay', 'Rays', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-26-2013 19:05:00', 'TEX', 'Texas', 'Rangers', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-26-2013 19:07:00', 'HOU', 'Houston', 'Astros', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-26-2013 19:08:00', 'PHI', 'Philadelphia', 'Phillies', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-26-2013 19:10:00', 'PIT', 'Pittsburgh', 'Pirates', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-26-2013 19:30:00', 'STL', 'St. Louis', 'Cardinals', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-26-2013 20:10:00', 'KC', 'Kansas City', 'Royals', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-26-2013 20:40:00', 'MIL', 'Milwaukee', 'Brewers', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-26-2013 21:40:00', 'SD', 'San Diego', 'Padres', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-26-2013 22:05:00', 'LAA', 'Anaheim', 'Angels', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-26-2013 22:10:00', 'CIN', 'Cincinatti', 'Reds', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-26-2013 22:10:00', 'MIN', 'Minnesota', 'Twins', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-26-2013 22:15:00', 'CHC', 'Chicago', 'Cubs', 'SF', 'San Francisco', 'Giants');





--July 27, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-27-2013 13:05:00', 'TB', 'Tampa Bay', 'Rays', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-27-2013 13:07:00', 'HOU', 'Houston', 'Astros', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-27-2013 15:05:00', 'LAA', 'Anaheim', 'Angels', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-27-2013 15:05:00', 'NYM', 'New York', 'Mets', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-27-2013 15:05:00', 'STL', 'St. Louis', 'Cardinals', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-27-2013 16:10:00', 'MIN', 'Minnesota', 'Twins', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-27-2013 19:05:00', 'BOS', 'Boston', 'Red Sox', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-27-2013 19:05:00', 'TEX', 'Texas', 'Rangers', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-27-2013 19:08:00', 'PHI', 'Philadelphia', 'Phillies', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-27-2013 19:10:00', 'KC', 'Kansas City', 'Royals', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-27-2013 19:10:00', 'PIT', 'Pittsburgh', 'Pirates', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-27-2013 20:10:00', 'MIL', 'Milwaukee', 'Brewers', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-27-2013 20:10:00', 'SD', 'San Diego', 'Padres', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-27-2013 21:05:00', 'CHC', 'Chicago', 'Cubs', 'SF', 'San Francisco', 'Giants');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-27-2013 21:10;00', 'CIN', 'Cincinatti', 'Reds', 'LAD', 'Los Angeles', 'Dodgers');





--July 28, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-28-2013 13:05:00', 'TB', 'Tampa Bay', 'Rays', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-28-2013 13:05:00', 'TEX', 'Texas', 'Rangers', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-28-2013 13:07:00', 'HOU', 'Houston', 'Astros', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-28-2013 13:08:00', 'PHI', 'Philadelphia', 'Phillies', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-28-2013 13:10:00', 'PIT', 'Pittsburgh', 'Pirates', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-28-2013 13:35:00', 'BOS', 'Boston', 'Red Sox', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-28-2013 13:35:00', 'NYM', 'New York', 'Mets', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-28-2013 13:35:00', 'STL', 'St. Louis', 'Cardinals', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-28-2013 14:10:00', 'KC', 'Kansas City', 'Royals', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-28-2013 16:05:00', 'LAA', 'Anaheim', 'Angels', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-28-2013 16:05:00', 'CHC', 'Chicago', 'Cubs', 'SF', 'San Francisco', 'Giants');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-28-2013 16:10:00', 'CIN', 'Cincinatti', 'Reds', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-28-2013 16:10:00', 'MIL', 'Milwaukee', 'Brewers', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-28-2013 16:10:00', 'MIN', 'Minnesota', 'Twins', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-28-2013 16:10:00', 'SD', 'San Diego', 'Padres', 'ARI', 'Arizona', 'Diamondbacks');





--July 29, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-29-2013 19:05:00', 'CHW', 'Chicago', 'White Sox', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-29-2013 19:05:00', 'STL', 'St. Louis', 'Cardinals', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-29-2013 19:10:00', 'COL', 'Colorado', 'Rockies', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-29-2013 19:10:00', 'NYM', 'New York', 'Mets', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-29-2013 20:05:00', 'LAA', 'Anaheim', 'Angels', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-29-2013 20:05:00', 'MIL', 'Milwaukee', 'Brewers', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-29-2013 22:05:00', 'TOR', 'Toronto', 'Blue Jays', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-29-2013 22:10:00', 'CIN', 'Cincinatti', 'Reds', 'SD', 'San Diego', 'Padres');





--July 30, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-30-2013 14:20:00', 'MIL', 'Milwaukee', 'Brewers', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-30-2013 16:05:00', 'STL', 'St. Louis', 'Cardinals', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-30-2013 19:05:00', 'CHW', 'Chicago', 'White Sox', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-30-2013 19:05:00', 'HOU', 'Houston', 'Astros', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-30-2013 19:05:00', 'SF', 'San Francisco', 'Giants', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-30-2013 19:08:00', 'WSH', 'Washington D.C.', 'Nationals', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-30-2013 19:10:00', 'ARI', 'Arizona', 'Diamondbacks', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-30-2013 19:10:00', 'COL', 'Colorado', 'Rockies', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-30-2013 19:10:00', 'NYM', 'New York', 'Mets', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-30-2013 19:10:00', 'SEA', 'Seattle', 'Mariners', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-30-2013 20:05:00', 'LAA', 'Anaheim', 'Angels', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-30-2013 20:05:00', 'MIL', 'Milwaukee', 'Brewers', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-30-2013 20:10:00', 'KC', 'Kansas City', 'Royals', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-30-2013 22:05:00', 'TOR', 'Toronto', 'Blue Jays', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-30-2013 22:10:00', 'CIN', 'Cincinatti', 'Reds', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-30-2013 22:10:00', 'NYY', 'New York', 'Yankees', 'LAD', 'Los Angeles', 'Dodgers');





--July 31, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-31-2013 13:08:00', 'WSH', 'Washington D.C.', 'Nationals', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-31-2013 15:35:00', 'TOR', 'Toronto', 'Blue Jays', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-31-2013 15:40:00', 'CIN', 'Cincinatti', 'Reds', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-31-2013 19:05:00', 'CHW', 'Chicago', 'White Sox', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-31-2013 19:05:00', 'HOU', 'Houston', 'Astros', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-31-2013 19:05:00', 'SF', 'San Francisco', 'Giants', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-31-2013 19:05:00', 'STL', 'St. Louis', 'Cardinals', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-31-2013 19:10:00', 'ARI', 'Arizona', 'Diamondbacks', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-31-2013 19:10:00', 'COL', 'Colorado', 'Rockies', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-31-2013 19:10:00', 'NYM', 'New York', 'Mets', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-31-2013 19:10:00', 'SEA', 'Seattle', 'Mariners', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-31-2013 20:05:00', 'LAA', 'Anaheim', 'Angels', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-31-2013 20:05:00', 'MIL', 'Milwaukee', 'Brewers', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-31-2013 20:10:00', 'KC', 'Kansas City', 'Royals', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '7-31-2013 22:10:00', 'NYY', 'New York', 'Yankees', 'LAD', 'Los Angeles', 'Dodgers');
