--June 1, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-1-2013 13:05:00', 'TB', 'Tampa Bay', 'Rays', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-1-2013 13:10:00', 'SEA', 'Seattle', 'Mariners', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-1-2013 16:05:00', 'CHW', 'Chicago', 'White Sox', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-1-2013 16:05:00', 'DET', 'Detroit', 'Tigers', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-1-2013 16:05:00', 'KC', 'Kansas City', 'Royals', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-1-2013 16:05:00', 'MIL', 'Milwaukee', 'Brewers', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-1-2013 16:10:00', 'LAD', 'Los Angeles', 'Dodgers', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-1-2013 16:10:00', 'NYM', 'New York', 'Mets', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-1-2013 19:15:00', 'ARI', 'Arizona', 'Diamondbacks', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-1-2013 19:15:00', 'BOS', 'Boston', 'Red Sox', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-1-2013 19:15:00', 'CIN', 'Cincinatti', 'Reds', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-1-2013 19:15:00', 'SF', 'San Francisco', 'Giants', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-1-2013 19:15:00', 'WSH', 'Washington D.C.', 'Nationals', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-1-2013 22:05:00', 'HOU', 'Houston', 'Astros', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-1-2013 22:10:00', 'TOR', 'Toronto', 'Blue Jays', 'SD', 'San Diego', 'Padres');




--June 2, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-2-2013 13:05:00', 'TB', 'Tampa Bay', 'Rays', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-2-2013 13:10:00', 'NYM', 'New York', 'Mets', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-2-2013 13:35:00', 'CIN', 'Cincinatti', 'Reds', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-2-2013 13:35:00', 'DET', 'Detroit', 'Tigers', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-2-2013 13:35:00', 'MIL', 'Milwaukee', 'Brewers', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-2-2013 13:35:00', 'WSH', 'Washington D.C.', 'Nationals', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-2-2013 14:10:00', 'SEA', 'Seattle', 'Mariners', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-2-2013 14:15:00', 'SF', 'San Francisco', 'Giants', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-2-2013 14:20:00', 'ARI', 'Arizona', 'Diamondbacks', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-2-2013 15:05:00', 'KC', 'Kansas City', 'Royals', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-2-2013 15:35:00', 'HOU', 'Houston', 'Astros', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-2-2013 16:05:00', 'CHW', 'Chicago', 'White Sox', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-2-2013 16:10:00', 'LAD', 'Los Angeles', 'Dodgers', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-2-2013 20:00:00', 'BOS', 'Boston', 'Red Sox', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-2-2013 22:10:00', 'TOR', 'Toronto', 'Blue Jays', 'SD', 'San Diego', 'Padres');




--June 3, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-3-2013 19:05:00', 'CLE', 'Cleveland', 'Indians', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-3-2013 19:05:00', 'MIA', 'Miami', 'Marlins', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-3-2013 19:10:00', 'COL', 'Colorado', 'Rockies', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-3-2013 19:10:00', 'PIT', 'Pittsburgh', 'Pirates', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-3-2013 20:10:00', 'OAK', 'Oakland', 'Athletics', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-3-2013 20:15:00', 'ARI', 'Arizona', 'Diamondbacks', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-3-2013 22:05:00', 'HOU', 'Houston', 'Astros', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-3-2013 22:10:00', 'CHW', 'Chicago', 'White Sox', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-3-2013 22:10:00', 'SD', 'San Diego', 'Padres', 'LAD', 'Los Angeles', 'Dodgers');




--June 4, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-4-2013 19:05:00', 'CLE', 'Cleveland', 'Indians', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-4-2013 19:05:00', 'MIA', 'Miami', 'Marlins', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-4-2013 19:05:00', 'NYM', 'New York', 'Mets', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-4-2013 19:08:00', 'TB', 'Tampa Bay', 'Rays', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-4-2013 19:10:00', 'COL', 'Colorado', 'Rockies', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-4-2013 19:10:00', 'PIT', 'Pittsburgh', 'Pirates', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-4-2013 19:10:00', 'TEX', 'Texas', 'Rangers', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-4-2013 20:10:00', 'BAL', 'Baltimore', 'Orioles', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-4-2013 20:10:00', 'MIN', 'Minnesota', 'Twins', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-4-2013 20:10:00', 'OAK', 'Oakland', 'Athletics', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-4-2013 20:15:00', 'ARI', 'Arizona', 'Diamondbacks', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-4-2013 22:05:00', 'CHC', 'Chicago', 'Cubs', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-4-2013 22:10:00', 'CHW', 'Chicago', 'White Sox', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-4-2013 22:10:00', 'SD', 'San Diego', 'Padres', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-4-2013 22:15:00', 'TOR', 'Toronto', 'Blue Jays', 'SF', 'San Francisco', 'Giants');




--June 5, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-5-2013 12:10:00', 'PIT', 'Pittsburgh', 'Pirates', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-5-2013 13:05:00', 'CLE', 'Cleveland', 'Indians', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-5-2013 13:05:00', 'MIA', 'Miami', 'Marlins', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-5-2013 14:10:00', 'OAK', 'Oakland', 'Athletics', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-5-2013 15:40:00', 'CHW', 'Chicago', 'White Sox', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-5-2013 15:45:00', 'TOR', 'Toronto', 'Blue Jays', 'SF', 'San Francisco', 'Giants');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-5-2013 19:05:00', 'CHC', 'Chicago', 'Cubs', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-5-2013 19:05:00', 'NYM', 'New York', 'Mets', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-5-2013 19:08:00', 'TB', 'Tampa Bay', 'Rays', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-5-2013 19:10:00', 'COL', 'Colorado', 'Rockies', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-5-2013 19:10:00', 'TEX', 'Texas', 'Rangers', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-5-2013 20:10:00', 'BAL', 'Baltimore', 'Orioles', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-5-2013 20:10:00', 'MIN', 'Minnesota', 'Twins', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-5-2013 20:15:00', 'ARI', 'Arizona', 'Diamondbacks', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-5-2013 22:10:00', 'SD', 'San Diego', 'Padres', 'LAD', 'Los Angeles', 'Dodgers');




--June 6, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-6-2013 13:08:00', 'TB', 'Tampa Bay', 'Rays', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-6-2013 14:10:00', 'BAL', 'Baltimore', 'Orioles', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-6-2013 19:05:00', 'NYM', 'New York', 'Mets', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-6-2013 19:10:00', 'TEX', 'Texas', 'Rangers', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-6-2013 19:15:00', 'ARI', 'Arizona', 'Diamondbacks', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-6-2013 20:10:00', 'MIN', 'Minnesota', 'Twins', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-6-2013 20:10:00', 'OAK', 'Oakland', 'Athletics', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-6-2013 20:10:00', 'PHI', 'Philadelphia', 'Phillies', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-6-2013 20:40:00', 'SD', 'San Diego', 'Padres', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-6-2013 22:10:00', 'ATL', 'Atlanta', 'Braves', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-6-2013 22:10:00', 'NYY', 'New York', 'Yankees', 'SEA', 'Seattle', 'Mariners');




--June 7, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-7-2013 14:20:00', 'PIT', 'Pittsburgh', 'Pirates', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-7-2013 19:05:00', 'MIN', 'Minnesota', 'Twins', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-7-2013 19:07:00', 'TEX', 'Texas', 'Rangers', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-7-2013 19:08:00', 'CLE', 'Cleveland', 'Indians', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-7-2013 19:10:00', 'LAA', 'Anaheim', 'Angels', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-7-2013 19:10:00', 'BAL', 'Baltimore', 'Orioles', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-7-2013 19:10:00', 'MIA', 'Miami', 'Marlins', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-7-2013 19:10:00', 'STL', 'St. Louis', 'Cardinals', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-7-2013 20:10:00', 'HOU', 'Houston', 'Astros', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-7-2013 20:10:00', 'OAK', 'Oakland', 'Athletics', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-7-2013 20:10:00', 'PHI', 'Philadelphia', 'Phillies', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-7-2013 20:40:00', 'SD', 'San Diego', 'Padres', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-7-2013 21:40:00', 'SF', 'San Francisco', 'Giants', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-7-2013 22:10:00', 'ATL', 'Atlanta', 'Braves', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-7-2013 22:10:00', 'NYY', 'New York', 'Yankees', 'SEA', 'Seattle', 'Mariners');




--June 8, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-8-2013 13:07:00', 'TEX', 'Texas', 'Rangers', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-8-2013 13:10:00', 'MIA', 'Miami', 'Marlins', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-8-2013 16:05:00', 'MIN', 'Minnesota', 'Twins', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-8-2013 16:05:00', 'PIT', 'Pittsburgh', 'Pirates', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-8-2013 16:08:00', 'CLE', 'Cleveland', 'Indians', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-8-2013 16:10:00', 'BAL', 'Baltimore', 'Orioles', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-8-2013 16:10:00', 'NYY', 'New York', 'Yankees', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-8-2013 16:10:00', 'OAK', 'Oakland', 'Athletics', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-8-2013 19:15:00', 'LAA', 'Anaheim', 'Angels', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-8-2013 19:15:00', 'HOU', 'Houston', 'Astros', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-8-2013 19:15:00', 'PHI', 'Philadelphia', 'Phillies', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-8-2013 19:15:00', 'SD', 'San Diego', 'Padres', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-8-2013 19:15:00', 'STL', 'St. Louis', 'Cardinals', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-8-2013 22:10:00', 'ATL', 'Atlanta', 'Braves', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-8-2013 22:10:00', 'SF', 'San Francisco', 'Giants', 'ARI', 'Arizona', 'Diamondbacks');




--June 9, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-9-2013 13:07:00', 'TEX', 'Texas', 'Rangers', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-9-2013 13:08:00', 'CLE', 'Cleveland', 'Indians', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-9-2013 13:10:00', 'MIA', 'Miami', 'Marlins', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-9-2013 13:35:00', 'LAA', 'Anaheim', 'Angels', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-9-2013 13:35:00', 'MIN', 'Minnesota', 'Twins', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-9-2013 13:40:00', 'BAL', 'Baltimore', 'Orioles', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-9-2013 14:10:00', 'HOU', 'Houston', 'Astros', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-9-2013 14:10:00', 'OAK', 'Oakland', 'Athletics', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-9-2013 14:10:00', 'PHI', 'Philadelphia', 'Phillies', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-9-2013 14:20:00', 'PIT', 'Pittsburgh', 'Pirates', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-9-2013 16:10:00', 'ATL', 'Atlanta', 'Braves', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-9-2013 16:10:00', 'NYY', 'New York', 'Yankees', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-9-2013 16:10:00', 'SD', 'San Diego', 'Padres', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-9-2013 16:10:00', 'SF', 'San Francisco', 'Giants', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-9-2013 20:05:00', 'STL', 'St. Louis', 'Cardinals', 'CIN', 'Cincinatti', 'Reds');




--June 10, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-10-2013 19:05:00', 'LAA', 'Anaheim', 'Angels', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-10-2013 19:10:00', 'BOS', 'Boston', 'Red Sox', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-10-2013 19:10:00', 'MIL', 'Milwaukee', 'Brewers', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-10-2013 20:05:00', 'CIN', 'Cincinatti', 'Reds', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-10-2013 20:05:00', 'CLE', 'Cleveland', 'Indians', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-10-2013 20:10:00', 'DET', 'Detroit', 'Tigers', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-10-2013 20:10:00', 'TOR', 'Toronto', 'Blue Jays', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-10-2013 22:10:00', 'ARI', 'Arizona', 'Diamondbacks', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-10-2013 22:10:00', 'ATL', 'Atlanta', 'Braves', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-10-2013 22:10:00', 'HOU', 'Houston', 'Astros', 'SEA', 'Seattle', 'Mariners');




--June 11, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-11-2013 19:05:00', 'LAA', 'Anaheim', 'Angels', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-11-2013 19:05:00', 'SF', 'San Francisco', 'Giants', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-11-2013 19:10:00', 'BOS', 'Boston', 'Red Sox', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-11-2013 19:10:00', 'MIL', 'Milwaukee', 'Brewers', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-11-2013 19:10:00', 'STL', 'St. Louis', 'Cardinals', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-11-2013 20:05:00', 'CIN', 'Cincinatti', 'Reds', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-11-2013 20:05:00', 'CLE', 'Cleveland', 'Indians', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-11-2013 20:10:00', 'DET', 'Detroit', 'Tigers', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-11-2013 20:10:00', 'PHI', 'Philadelphia', 'Phillies', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-11-2013 20:10:00', 'TOR', 'Toronto', 'Blue Jays', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-11-2013 20:40:00', 'WSH', 'Washington D.C.', 'Nationals', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-11-2013 22:05:00', 'NYY', 'New York', 'Yankees', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-11-2013 22:10:00', 'ARI', 'Arizona', 'Diamondbacks', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-11-2013 22:10:00', 'ATL', 'Atlanta', 'Braves', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-11-2013 22:10:00', 'HOU', 'Houston', 'Astros', 'SEA', 'Seattle', 'Mariners');




--June 12, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-12-2013 12:35:00', 'LAA', 'Anaheim', 'Angels', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-12-2013 14:10:00', 'DET', 'Detroit', 'Tigers', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-12-2013 14:20:00', 'CIN', 'Cincinatti', 'Reds', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-12-2013 15:40:00', 'ATL', 'Atlanta', 'Braves', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-12-2013 19:05:00', 'SF', 'San Francisco', 'Giants', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-12-2013 19:10:00', 'BOS', 'Boston', 'Red Sox', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-12-2013 19:10:00', 'MIL', 'Milwaukee', 'Brewers', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-12-2013 19:10:00', 'STL', 'St. Louis', 'Cardinals', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-12-2013 20:05:00', 'CLE', 'Cleveland', 'Indians', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-12-2013 20:10:00', 'PHI', 'Philadelphia', 'Phillies', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-12-2013 20:10:00', 'TOR', 'Toronto', 'Blue Jays', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-12-2013 20:40:00', 'WSH', 'Washington D.C.', 'Nationals', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-12-2013 22:05:00', 'NYY', 'New York', 'Yankees', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-12-2013 22:10:00', 'ARI', 'Arizona', 'Diamondbacks', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-12-2013 22:10:00', 'HOU', 'Houston', 'Astros', 'SEA', 'Seattle', 'Mariners');




--June 13, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-13-2013 13:10:00', 'STL', 'St. Louis', 'Cardinals', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-13-2013 14:20:00', 'CIN', 'Cincinatti', 'Reds', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-13-2013 15:10:00', 'WSH', 'Washington D.C.', 'Nationals', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-13-2013 15:35:00', 'NYY', 'New York', 'Yankees', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-13-2013 19:05:00', 'BOS', 'Boston', 'Red Sox', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-13-2013 19:05:00', 'SF', 'San Francisco', 'Giants', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-13-2013 19:10:00', 'KC', 'Kansas City', 'Royals', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-13-2013 20:05:00', 'TOR', 'Toronto', 'Blue Jays', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-13-2013 20:10:00', 'PHI', 'Philadelphia', 'Phillies', 'MIN', 'Minnesota', 'Twins');




--June 14, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-14-2013 19:05:00', 'BOS', 'Boston', 'Red Sox', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-14-2013 19:05:00', 'LAD', 'Los Angeles', 'Dodgers', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-14-2013 19:05:00', 'WSH', 'Washington D.C.', 'Nationals', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-14-2013 19:10:00', 'CHC', 'Chicago', 'Cubs', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-14-2013 19:10:00', 'KC', 'Kansas City', 'Royals', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-14-2013 19:10:00', 'MIL', 'Milwaukee', 'Brewers', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-14-2013 19:10:00', 'STL', 'St. Louis', 'Cardinals', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-14-2013 19:30:00', 'SF', 'San Francisco', 'Giants', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-14-2013 20:05:00', 'TOR', 'Toronto', 'Blue Jays', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-14-2013 20:10:00', 'CHW', 'Chicago', 'White Sox', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-14-2013 20:10:00', 'DET', 'Detroit', 'Tigers', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-14-2013 20:40:00', 'PHI', 'Philadelphia', 'Phillies', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-14-2013 22:05:00', 'NYY', 'New York', 'Yankees', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-14-2013 22:05:00', 'SEA', 'Seattle', 'Mariners', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-14-2013 22:10:00', 'ARI', 'Arizona', 'Diamondbacks', 'SD', 'San Diego', 'Padres');




--June 15, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-15-2013 13:10:00', 'CHC', 'Chicago', 'Cubs', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-15-2013 16:05:00', 'BOS', 'Boston', 'Red Sox', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-15-2013 16:05:00', 'LAD', 'Los Angeles', 'Dodgers', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-15-2013 16:05:00', 'SF', 'San Francisco', 'Giants', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-15-2013 16:05:00', 'TOR', 'Toronto', 'Blue Jays', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-15-2013 16:10:00', 'KC', 'Kansas City', 'Royals', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-15-2013 16:10:00', 'MIL', 'Milwaukee', 'Brewers', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-15-2013 16:10:00', 'PHI', 'Philadelphia', 'Phillies', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-15-2013 16:10:00', 'STL', 'St. Louis', 'Cardinals', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-15-2013 19:15:00', 'CHW', 'Chicago', 'White Sox', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-15-2013 19:15:00', 'DET', 'Detroit', 'Tigers', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-15-2013 19:15:00', 'NYY', 'New York', 'Yankees', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-15-2013 19:15:00', 'SEA', 'Seattle', 'Mariners', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-15-2013 19:15:00', 'WSH', 'Washington D.C.', 'Nationals', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-15-2013 22:10:00', 'ARI', 'Arizona', 'Diamondbacks', 'SD', 'San Diego', 'Padres');




--June 16, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-16-2013 00:00:00', 'NYY', 'New York', 'Yankees', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-16-2013 13:05:00', 'WSH', 'Washington D.C.', 'Nationals', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-16-2013 13:10:00', 'CHC', 'Chicago', 'Cubs', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-16-2013 13:10:00', 'MIL', 'Milwaukee', 'Brewers', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-16-2013 13:10:00', 'STL', 'St. Louis', 'Cardinals', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-16-2013 13:35:00', 'BOS', 'Boston', 'Red Sox', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-16-2013 13:35:00', 'LAD', 'Los Angeles', 'Dodgers', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-16-2013 13:35:00', 'SF', 'San Francisco', 'Giants', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-16-2013 13:40:00', 'KC', 'Kansas City', 'Royals', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-16-2013 14:10:00', 'CHW', 'Chicago', 'White Sox', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-16-2013 14:10:00', 'DET', 'Detroit', 'Tigers', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-16-2013 15:05:00', 'TOR', 'Toronto', 'Blue Jays', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-16-2013 16:05:00', 'SEA', 'Seattle', 'Mariners', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-16-2013 16:10:00', 'ARI', 'Arizona', 'Diamondbacks', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-16-2013 16:10:00', 'PHI', 'Philadelphia', 'Phillies', 'COL', 'Colorado', 'Rockies');





--June 17, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-17-2013 19:05:00', 'CHC', 'Chicago', 'Cubs', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-17-2013 19:05:00', 'KC', 'Kansas City', 'Royals', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-17-2013 19:05:00', 'WSH', 'Washington D.C.', 'Nationals', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-17-2013 19:07:00', 'COL', 'Colorado', 'Rockies', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-17-2013 19:08:00', 'BAL', 'Baltimore', 'Orioles', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-17-2013 19:10:00', 'NYM', 'New York', 'Mets', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-17-2013 19:10:00', 'PIT', 'Pittsburgh', 'Pirates', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-17-2013 20:05:00', 'OAK', 'Oakland', 'Athletics', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-17-2013 20:10:00', 'CHW', 'Chicago', 'White Sox', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-17-2013 21:40:00', 'MIA', 'Miami', 'Marlins', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-17-2013 22:05:00', 'SEA', 'Seattle', 'Mariners', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-17-2013 22:15:00', 'SD', 'San Diego', 'Padres', 'SF', 'San Francisco', 'Giants');





--June 18, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-18-2013 13:05:00', 'TB', 'Tampa Bay', 'Rays', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-18-2013 13:10:00', 'NYM', 'New York', 'Mets', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-18-2013 19:05:00', 'KC 19:05:00', 'Kansas City', 'Royals', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-18-2013 19:05:00', 'LAD 19:05:00', 'Los Angeles', 'Dodgers', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-18-2013 19:05:00', 'WSH 19:05:00', 'Washington D.C.', 'Nationals', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-18-2013 19:07:00', 'COL', 'Colorado', 'Rockies', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-18-2013 19:08:00', 'BAL', 'Baltimore', 'Orioles', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-18-2013 19:10:00', 'NYM', 'New York', 'Mets', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-18-2013 19:10:00', 'PIT', 'Pittsburgh', 'Pirates', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-18-2013 19:10:00', 'TB', 'Tampa Bay', 'Rays', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-18-2013 20:05:00', 'OAK', 'Oakland', 'Athletics', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-18-2013 20:10:00', 'CHW', 'Chicago', 'White Sox', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-18-2013 20:10:00', 'MIL', 'Milwaukee', 'Brewers', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-18-2013 20:15:00', 'CHC', 'Chicago', 'Cubs', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-18-2013 21:40:00', 'MIA', 'Miami', 'Marlins', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-18-2013 22:05:00', 'SEA', 'Seattle', 'Mariners', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-18-2013 22:15:00', 'SD', 'San Diego', 'Padres', 'SF', 'San Francisco', 'Giants');






--June 19, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-19-2013 13:08:00', 'BAL', 'Baltimore', 'Orioles', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-19-2013 15:40:00', 'MIA', 'Miami', 'Marlins', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-19-2013 15:45:00', 'SD', 'San Diego', 'Padres', 'SF', 'San Francisco', 'Giants');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-19-2013 19:05:00', 'KC', 'Kansas City', 'Royals', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-19-2013 19:05:00', 'LAD', 'Los Angeles', 'Dodgers', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-19-2013 19:05:00', 'WSH', 'Washington D.C.', 'Nationals', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-19-2013 19:07:00', 'COL', 'Colorado', 'Rockies', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-19-2013 19:10:00', 'NYM', 'New York', 'Mets', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-19-2013 19:10:00', 'PIT', 'Pittsburgh', 'Pirates', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-19-2013 19:10:00', 'TB', 'Tampa Bay', 'Rays', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-19-2013 20:05:00', 'OAK', 'Oakland', 'Athletics', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-19-2013 20:10:00', 'CHW', 'Chicago', 'White Sox', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-19-2013 20:10:00', 'MIL', 'Milwaukee', 'Brewers', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-19-2013 20:15:00', 'CHC', 'Chicago', 'Cubs', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-19-2013 22:05:00', 'SEA', 'Seattle', 'Mariners', 'LAA', 'Anaheim', 'Angels');





--June 20, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-20-2013 12:35:00', 'PIT', 'Pittsburgh', 'Pirates', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-20-2013 13:10:00', 'CHW', 'Chicago', 'White Sox', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-20-2013 14:05:00', 'OAK', 'Oakland', 'Athletics', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-20-2013 14:10:00', 'MIL', 'Milwaukee', 'Brewers', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-20-2013 19:05:00', 'COL', 'Colorado', 'Rockies', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-20-2013 19:05:00', 'TB', 'Tampa Bay', 'Rays', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-20-2013 19:08:00', 'BOS', 'Boston', 'Red Sox', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-20-2013 19:10:00', 'NYM', 'New York', 'Mets', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-20-2013 20:15:00', 'CHC', 'Chicago', 'Cubs', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-20-2013 22:05:00', 'SEA', 'Seattle', 'Mariners', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-20-2013 22:10:00', 'LAD', 'Los Angeles', 'Dodgers', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-20-2013 22:15:00', 'MIA', 'Miami', 'Marlins', 'SF', 'San Francisco', 'Giants');





--June 21, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-21-2013 14:20:00', 'HOU', 'Houston', 'Astros', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-21-2013 19:05:00', 'COL', 'Colorado', 'Rockies', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-21-2013 19:05:00', 'MIN', 'Minnesota', 'Twins', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-21-2013 19:05:00', 'NYM', 'New York', 'Mets', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-21-2013 19:05:00', 'TB', 'Tampa Bay', 'Rays', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-21-2013 19:07:00', 'BAL', 'Baltimore', 'Orioles', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-21-2013 19:08:00', 'BOS', 'Boston', 'Red Sox', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-21-2013 20:10:00', 'ATL', 'Atlanta', 'Braves', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-21-2013 20:10:00', 'CHW', 'Chicago', 'White Sox', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-21-2013 20:15:00', 'TEX', 'Texas', 'Rangers', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-21-2013 21:40:00', 'CIN', 'Cincinatti', 'Reds', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-21-2013 22:05:00', 'PIT', 'Pittsburgh', 'Pirates', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-21-2013 22:10:00', 'LAD', 'Los Angeles', 'Dodgers', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-21-2013 22:10:00', 'OAK', 'Oakland', 'Athletics', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-21-2013 22:15:00', 'MIA', 'Miami', 'Marlins', 'SF', 'San Francisco', 'Giants');





--June 22, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-22-2013 12:05:00', 'COL', 'Colorado', 'Rockies', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-22-2013 13:05:00', 'TB', 'Tampa Bay', 'Rays', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-22-2013 13:07:00', 'BAL', 'Baltimore', 'Orioles', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-22-2013 14:10:00', 'CHW', 'Chicago', 'White Sox', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-22-2013 16:05:00', 'HOU', 'Houston', 'Astros', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-22-2013 16:05:00', 'MIA', 'Miami', 'Marlins', 'SF', 'San Francisco', 'Giants');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-22-2013 16:05:00', 'NYM', 'New York', 'Mets', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-22-2013 16:10:00', 'ATL', 'Atlanta', 'Braves', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-22-2013 19:15:00', 'BOS', 'Boston', 'Red Sox', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-22-2013 19:15:00', 'CIN', 'Cincinatti', 'Reds', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-22-2013 19:15:00', 'LAD', 'Los Angeles', 'Dodgers', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-22-2013 19:15:00', 'MIN', 'Minnesota', 'Twins', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-22-2013 19:15:00', 'TEX', 'Texas', 'Rangers', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-22-2013 22:05:00', 'PIT', 'Pittsburgh', 'Pirates', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-22-2013 22:10:00', 'OAK', 'Oakland', 'Athletics', 'SEA', 'Seattle', 'Mariners');





--June 23, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-23-2013 00:00:00', 'TB', 'Tampa Bay', 'Rays', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-23-2013 13:05:00', 'MIN', 'Minnesota', 'Twins', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-23-2013 13:07:00', 'BAL', 'Baltimore', 'Orioles', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-23-2013 13:08:00', 'BOS', 'Boston', 'Red Sox', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-23-2013 13:35:00', 'COL', 'Colorado', 'Rockies', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-23-2013 13:35:00', 'NYM', 'New York', 'Mets', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-23-2013 14:10:00', 'ATL', 'Atlanta', 'Braves', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-23-2013 14:10:00', 'CHW', 'Chicago', 'White Sox', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-23-2013 14:15:00', 'TEX', 'Texas', 'Rangers', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-23-2013 14:20:00', 'HOU', 'Houston', 'Astros', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-23-2013 15:35:00', 'PIT', 'Pittsburgh', 'Pirates', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-23-2013 16:05:00', 'MIA', 'Miami', 'Marlins', 'SF', 'San Francisco', 'Giants');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-23-2013 16:10:00', 'CIN', 'Cincinatti', 'Reds', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-23-2013 16:10:00', 'LAD', 'Los Angeles', 'Dodgers', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-23-2013 16:10:00', 'OAK', 'Oakland', 'Athletics', 'SEA', 'Seattle', 'Mariners');





--June 24, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-24-2013 19:05:00', 'CLE', 'Cleveland', 'Indians', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-24-2013 19:10:00', 'TOR', 'Toronto', 'Blue Jays', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-24-2013 22:10:00', 'PHI', 'Philadelphia', 'Phillies', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-24-2013 22:10:00', 'SF', 'San Francisco', 'Giants', 'LAD', 'Los Angeles', 'Dodgers');





--June 25, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-25-2013 19:05:00', 'ARI', 'Arizona', 'Diamondbacks', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-25-2013 19:05:00', 'CLE', 'Cleveland', 'Indians', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-25-2013 19:05:00', 'TEX', 'Texas', 'Rangers', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-25-2013 19:08:00', 'LAA', 'Anaheim', 'Angels', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-25-2013 19:10:00', 'COL', 'Colorado', 'Rockies', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-25-2013 19:10:00', 'MIN', 'Minnesota', 'Twins', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-25-2013 19:10:00', 'TOR', 'Toronto', 'Blue Jays', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-25-2013 20:10:00', 'ATL', 'Atlanta', 'Braves', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-25-2013 20:10:00', 'CHC', 'Chicago', 'Cubs', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-25-2013 20:10:00', 'NYM', 'New York', 'Mets', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-25-2013 20:10:00', 'STL', 'St. Louis', 'Cardinals', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-25-2013 22:05:00', 'CIN', 'Cincinatti', 'Reds', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-25-2013 22:10:00', 'PHI', 'Philadelphia', 'Phillies', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-25-2013 22:10:00', 'PIT', 'Pittsburgh', 'Pirates', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-25-2013 22:10:00', 'SF', 'San Francisco', 'Giants', 'LAD', 'Los Angeles', 'Dodgers');





--June 26, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-26-2013 12:10:00', 'TOR', 'Toronto', 'Blue Jays', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-26-2013 12:40:00', 'MIN', 'Minnesota', 'Twins', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-26-2013 15:35:00', 'CIN', 'Cincinatti', 'Reds', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-26-2013 15:40:00', 'PIT', 'Pittsburgh', 'Pirates', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-26-2013 16:05:00', 'COL', 'Colorado', 'Rockies', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-26-2013 19:05:00', 'ARI', 'Arizona', 'Diamondbacks', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-26-2013 19:05:00', 'CLE', 'Cleveland', 'Indians', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-26-2013 19:05:00', 'TEX', 'Texas', 'Rangers', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-26-2013 19:08:00', 'LAA', 'Anaheim', 'Angels', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-26-2013 20:10:00', 'ATL', 'Atlanta', 'Braves', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-26-2013 20:10:00', 'CHC', 'Chicago', 'Cubs', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-26-2013 20:10:00', 'NYM', 'New York', 'Mets', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-26-2013 20:10:00', 'STL', 'St. Louis', 'Cardinals', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-26-2013 22:10:00', 'PHI', 'Philadelphia', 'Phillies', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-26-2013 22:10:00', 'SF', 'San Francisco', 'Giants', 'LAD', 'Los Angeles', 'Dodgers');





--June 27, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-27-2013 13:05:00', 'TEX', 'Texas', 'Rangers', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-27-2013 13:08:00', 'LAA', 'Anaheim', 'Angels', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-27-2013 14:10:00', 'CHC', 'Chicago', 'Cubs', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-27-2013 16:05:00', 'ARI', 'Arizona', 'Diamondbacks', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-27-2013 18:10:00', 'NYM', 'New York', 'Mets', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-27-2013 19:05:00', 'CLE', 'Cleveland', 'Indians', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-27-2013 19:10:00', 'TOR', 'Toronto', 'Blue Jays', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-27-2013 20:10:00', 'KC', 'Kansas City', 'Royals', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-27-2013 22:10:00', 'PHI', 'Philadelphia', 'Phillies', 'LAD', 'Los Angeles', 'Dodgers');




--June 28, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-28-2013 17:10:00', 'CLE', 'Cleveland', 'Indians', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-28-2013 00:00:00', 'CLE', 'Cleveland', 'Indians', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-28-2013 19:05:00', 'MIL', 'Milwaukee', 'Brewers', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-28-2013 19:05:00', 'NYY', 'New York', 'Yankees', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-28-2013 19:10:00', 'DET', 'Detroit', 'Tigers', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-28-2013 19:10:00', 'SD', 'San Diego', 'Padres', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-28-2013 19:10:00', 'TOR', 'Toronto', 'Blue Jays', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-28-2013 19:10:00', 'WSH', 'Washington D.C.', 'Nationals', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-28-2013 19:30:00', 'ARI', 'Arizona', 'Diamondbacks', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-28-2013 20:05:00', 'CIN', 'Cincinatti', 'Reds', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-28-2013 20:10:00', 'LAA', 'Anaheim', 'Angels', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-28-2013 20:10:00', 'KC', 'Kansas City', 'Royals', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-28-2013 20:40:00', 'SF', 'San Francisco', 'Giants', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-28-2013 22:05:00', 'STL', 'St. Louis', 'Cardinals', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-28-2013 22:10:00', 'CHC', 'Chicago', 'Cubs', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-28-2013 22:10:00', 'PHI', 'Philadelphia', 'Phillies', 'LAD', 'Los Angeles', 'Dodgers');






--June 29, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-29-2013 13:10:00', 'WSH', 'Washington D.C.', 'Nationals', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-29-2013 16:05:00', 'ARI', 'Arizona', 'Diamondbacks', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-29-2013 16:05:00', 'STL', 'St. Louis', 'Cardinals', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-29-2013 16:05:00', 'TOR', 'Toronto', 'Blue Jays', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-29-2013 16:10:00', 'LAA', 'Anaheim', 'Angels', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-29-2013 16:10:00', 'CLE', 'Cleveland', 'Indians', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-29-2013 16:10:00', 'KC', 'Kansas City', 'Royals', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-29-2013 16:10:00', 'SF', 'San Francisco', 'Giants', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-29-2013 19:10:00', 'SD', 'San Diego', 'Padres', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-29-2013 19:15:00', 'CHC', 'Chicago', 'Cubs', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-29-2013 19:15:00', 'CIN', 'Cincinatti', 'Reds', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-29-2013 19:15:00', 'DET', 'Detroit', 'Tigers', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-29-2013 19:15:00', 'MIL', 'Milwaukee', 'Brewers', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-29-2013 19:15:00', 'NYY', 'New York', 'Yankees', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-29-2013 22:10:00', 'PHI', 'Philadelphia', 'Phillies', 'LAD', 'Los Angeles', 'Dodgers');





--June 30, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-30-2013 00:00:00', 'PHI', 'Philadelphia', 'Phillies', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-30-2013 13:10:00', 'SD', 'San Diego', 'Padres', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-30-2013 13:10:00', 'WSH', 'Washington D.C.', 'Nationals', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-30-2013 13:35:00', 'ARI', 'Arizona', 'Diamondbacks', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-30-2013 13:35:00', 'MIL', 'Milwaukee', 'Brewers', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-30-2013 13:35:00', 'NYY', 'New York', 'Yankees', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-30-2013 13:35:00', 'TOR', 'Toronto', 'Blue Jays', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-30-2013 13:40:00', 'DET', 'Detroit', 'Tigers', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-30-2013 14:10:00', 'LAA', 'Anaheim', 'Angels', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-30-2013 14:10:00', 'CLE', 'Cleveland', 'Indians', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-30-2013 14:10:00', 'KC', 'Kansas City', 'Royals', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-30-2013 15:05:00', 'CIN', 'Cincinatti', 'Reds', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-30-2013 16:05:00', 'STL', 'St. Louis', 'Cardinals', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-30-2013 16:10:00', 'CHC', 'Chicago', 'Cubs', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '6-30-2013 16:10:00', 'SF', 'San Francisco', 'Giants', 'COL', 'Colorado', 'Rockies');
