CREATE TABLE TEAM (
_id TEXT PRIMARY KEY,
CITY TEXT NOT NULL,
NAME TEXT NOT NULL);

CREATE TABLE GAME (
	_id INTEGER PRIMARY KEY AUTOINCREMENT,
	DATE TEXT NOT NULL,
	AWAY_TEAM_CITY TEXT NOT NULL,
	AWAY_TEAM_NAME TEXT NOT NULL,
	HOME_TEAM_CITY TEXT NOT NULL,
	HOME_TEAM_NAME TEXT NOT NULL);

INSERT INTO TEAM VALUES('NYY', 'New York', 'Yankees');
INSERT INTO TEAM VALUES('BOS', 'Boston', 'Red Sox');
INSERT INTO TEAM VALUES('TOR', 'Toronto', 'Blue Jays');
INSERT INTO TEAM VALUES('BAL', 'Baltimore', 'Orioles');
INSERT INTO TEAM VALUES('TB', 'Tampa Bay', 'Rays');

INSERT INTO TEAM VALUES('MIN', 'Minnesota', 'Twins');
INSERT INTO TEAM VALUES('DET', 'Detroit', 'Tigers');
INSERT INTO TEAM VALUES('CHW', 'Chicago', 'White Sox');
INSERT INTO TEAM VALUES('KC', 'Kansas City', 'Royals');

INSERT INTO TEAM VALUES('LAA', 'Anaheim', 'Angels');
INSERT INTO TEAM VALUES('TEX', 'Texas', 'Rangers');
INSERT INTO TEAM VALUES('HOU', 'Houston', 'Astros');
INSERT INTO TEAM VALUES('OAK', 'Oakland', 'Athletics');
INSERT INTO TEAM VALUES('SEA', 'Seattle', 'Mariners');

INSERT INTO TEAM VALUES('NYM', 'New York', 'Mets');
INSERT INTO TEAM VALUES('MIA', 'Miami', 'Marlins');
INSERT INTO TEAM VALUES('PHI', 'Philadelphia', 'Phillies');
INSERT INTO TEAM VALUES('WSH', 'Washington D.C.', 'Nationals');
INSERT INTO TEAM VALUES('ATL', 'Atlanta', 'Braves');

INSERT INTO TEAM VALUES('CIN', 'Cincinatti', 'Reds');
INSERT INTO TEAM VALUES('STL', 'St. Louis', 'Cardinals');
INSERT INTO TEAM VALUES('CHC', 'Chicago', 'Cubs');
INSERT INTO TEAM VALUES('PIT', 'Pittsburgh', 'Pirates');

INSERT INTO TEAM VALUES('SF', 'San Francisco', 'Giants');
INSERT INTO TEAM VALUES('LAD', 'Los Angeles', 'Dodgers');
INSERT INTO TEAM VALUES('SD', 'San Diego', 'Padres');
INSERT INTO TEAM VALUES('COL', 'Colorado', 'Rockies');
INSERT INTO TEAM VALUES('ARI', 'Arizona', 'Diamondbacks');

INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES('5-10-2013', 'New York', 'Yankees', 'Kansas City', 'Royals');
INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '5-11-2013', 'New York', 'Yankees', 'Kansas City', 'Royals');
INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '5-12-2013', 'New York', 'Yankees', 'Kansas City', 'Royals');
INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '5-13-2013', 'New York', 'Yankees', 'Cleveland', 'Indians');
INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '5-13-2013', 'New York', 'Yankees', 'Cleveland', 'Indians');

INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '5-14-2013', 'Seattle', 'Mariners', 'New York', 'Yankees');
INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '5-15-2013', 'Seattle', 'Mariners', 'New York', 'Yankees');
INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '5-16-2013', 'Seattle', 'Mariners', 'New York', 'Yankees');

INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '5-17-2013', 'Toronto', 'Blue Jays', 'New York', 'Yankees');
INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '5-18-2013', 'Toronto', 'Blue Jays', 'New York', 'Yankees');
INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '5-19-2013', 'Toronto', 'Blue Jays', 'New York', 'Yankees');

INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '5-20-2013', 'New York', 'Yankees', 'Baltimore', 'Orioles');
INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '5-21-2013', 'New York', 'Yankees', 'Baltimore', 'Orioles');
INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '5-22-2013', 'New York', 'Yankees', 'Baltimore', 'Orioles');

INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '5-24-2013', 'New York', 'Yankees', 'Baltimore', 'Orioles');
INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '5-25-2013', 'New York', 'Yankees', 'Baltimore', 'Orioles');
INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '5-26-2013', 'New York', 'Yankees', 'Baltimore', 'Orioles');

INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '5-27-2013', 'New York', 'Yankees', 'New York', 'Mets');
INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '5-28-2013', 'New York', 'Yankees', 'New York', 'Mets');
INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '5-29-2013', 'New York', 'Mets', 'New York', 'Yankees');
INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '5-30-2013', 'New York', 'Mets', 'New York', 'Yankees');

INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '5-31-2013', 'Boston', 'Red Sox', 'New York', 'Yankees');
INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '6-1-2013', 'Boston', 'Red Sox', 'New York', 'Yankees');
INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '6-2-2013', 'Boston', 'Red Sox', 'New York', 'Yankees');

INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '6-3-2013', 'Cleveland', 'Indians', 'New York', 'Yankees');
INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '6-4-2013', 'Cleveland', 'Indians', 'New York', 'Yankees');
INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '6-5-2013', 'Cleveland', 'Indians', 'New York', 'Yankees');

INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '6-6-2013', 'New York', 'Yankees', 'Seattle', 'Mariners');
INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '6-7-2013', 'New York', 'Yankees', 'Seattle', 'Mariners');
INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '6-8-2013', 'New York', 'Yankees', 'Seattle', 'Mariners');
INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '6-9-2013', 'New York', 'Yankees', 'Seattle', 'Mariners');

INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '6-11-2013', 'New York', 'Yankees', 'Oakland', 'Athletics');
INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '6-12-2013', 'New York', 'Yankees', 'Oakland', 'Athletics');
INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '6-13-2013', 'New York', 'Yankees', 'Oakland', 'Athletics');

INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '6-14-2013', 'New York', 'Yankees', 'Anaheim', 'Angels');
INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '6-15-2013', 'New York', 'Yankees', 'Anaheim', 'Angels');
INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '6-16-2013', 'New York', 'Yankees', 'Anaheim', 'Angels');

INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '6-18-2013', 'Los Angeles', 'Dodgers', 'New York', 'Yankees');
INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '6-19-2013', 'Los Angeles', 'Dodgers', 'New York', 'Yankees');

INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '6-21-2013', 'Tampa Bay', 'Rays', 'New York', 'Yankees');
INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '6-22-2013', 'Tampa Bay', 'Rays', 'New York', 'Yankees');
INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '6-23-2013', 'Tampa Bay', 'Rays', 'New York', 'Yankees');
INSERT INTO GAME (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) 
	VALUES( '6-24-2013', 'Tampa Bay', 'Rays', 'New York', 'Yankees');


























