--September 1, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-1-2013 00:00:00', 'NYM', 'New York', 'Mets', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-1-2013 00:00:00', 'PHI', 'Philadelphia', 'Phillies', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-1-2013 13:05:00', 'BAL', 'Baltimore', 'Orioles', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-1-2013 13:07:00', 'KC', 'Kansas City', 'Royals', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-1-2013 13:08:00', 'CLE', 'Cleveland', 'Indians', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-1-2013 13:35:00', 'CHW', 'Chicago', 'White Sox', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-1-2013 13:35:00', 'STL', 'St. Louis', 'Cardinals', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-1-2013 14:10:00', 'LAA', 'Anaheim', 'Angels', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-1-2013 14:10:00', 'SEA', 'Seattle', 'Mariners', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-1-2013 15:05:00', 'MIN', 'Minnesota', 'Twins', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-1-2013 16:05:00', 'TB', 'Tampa Bay', 'Rays', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-1-2013 16:10:00', 'CIN', 'Cincinatti', 'Reds', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-1-2013 16:10:00', 'SD', 'San Diego', 'Padres', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-1-2013 16:10:00', 'SF', 'San Francisco', 'Giants', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-1-2013 17:00:00', 'MIA', 'Miami', 'Marlins', 'ATL', 'Atlanta', 'Braves');






--September 2, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-2-2013 13:05:00', 'CHW', 'Chicago', 'White Sox', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-2-2013 13:10:00', 'NYM', 'New York', 'Mets', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-2-2013 13:10:00', 'STL', 'St. Louis', 'Cardinals', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-2-2013 13:35:00', 'DET', 'Detroit', 'Tigers', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-2-2013 14:10:00', 'MIN', 'Minnesota', 'Twins', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-2-2013 14:10:00', 'PIT', 'Pittsburgh', 'Pirates', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-2-2013 14:10:00', 'SEA', 'Seattle', 'Mariners', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-2-2013 14:20:00', 'MIA', 'Miami', 'Marlins', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-2-2013 15:40:00', 'SF', 'San Francisco', 'Giants', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-2-2013 16:05:00', 'BAL', 'Baltimore', 'Orioles', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-2-2013 16:05:00', 'TEX', 'Texas', 'Rangers', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-2-2013 16:10:00', 'LAD', 'Los Angeles', 'Dodgers', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-2-2013 16:10:00', 'TOR', 'Toronto', 'Blue Jays', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-2-2013 19:05:00', 'WSH', 'Washington D.C.', 'Nationals', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-2-2013 21:05:00', 'TB', 'Tampa Bay', 'Rays', 'LAA', 'Anaheim', 'Angels');






--September 3, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-3-2013 19:05:00', 'BAL', 'Baltimore', 'Orioles', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-3-2013 19:05:00', 'CHW', 'Chicago', 'White Sox', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-3-2013 19:05:00', 'WSH', 'Washington D.C.', 'Nationals', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-3-2013 19:10:00', 'DET', 'Detroit', 'Tigers', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-3-2013 19:10:00', 'NYM', 'New York', 'Mets', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-3-2013 19:10:00', 'STL', 'St. Louis', 'Cardinals', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-3-2013 20:05:00', 'MIA', 'Miami', 'Marlins', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-3-2013 20:10:00', 'MIN', 'Minnesota', 'Twins', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-3-2013 20:10:00', 'PIT', 'Pittsburgh', 'Pirates', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-3-2013 20:10:00', 'SEA', 'Seattle', 'Mariners', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-3-2013 20:40:00', 'LAD', 'Los Angeles', 'Dodgers', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-3-2013 21:40:00', 'TOR', 'Toronto', 'Blue Jays', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-3-2013 21:40:00', 'TB', 'Tampa Bay', 'Rays', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-3-2013 22:05:00', 'TEX', 'Texas', 'Rangers', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-3-2013 22:10:00', 'SF', 'San Francisco', 'Giants', 'SD', 'San Diego', 'Padres');






--September 4, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-4-2013 12:10:00', 'NYM', 'New York', 'Mets', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-4-2013 14:10:00', 'MIN', 'Minnesota', 'Twins', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-4-2013 14:20:00', 'MIA', 'Miami', 'Marlins', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-4-2013 15:35:00', 'TEX', 'Texas', 'Rangers', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-4-2013 15:40:00', 'TOR', 'Toronto', 'Blue Jays', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-4-2013 18:40:00', 'SF', 'San Francisco', 'Giants', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-4-2013 19:05:00', 'BAL', 'Baltimore', 'Orioles', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-4-2013 19:05:00', 'CHW', 'Chicago', 'White Sox', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-4-2013 19:05:00', 'WSH', 'Washington D.C.', 'Nationals', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-4-2013 19:10:00', 'DET', 'Detroit', 'Tigers', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-4-2013 19:10:00', 'STL', 'St. Louis', 'Cardinals', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-4-2013 20:10:00', 'PIT', 'Pittsburgh', 'Pirates', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-4-2013 20:10:00', 'SEA', 'Seattle', 'Mariners', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-4-2013 20:40:00', 'LAD', 'Los Angeles', 'Dodgers', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-4-2013 22:05:00', 'TB', 'Tampa Bay', 'Rays', 'LAA', 'Anaheim', 'Angels');






--September 5, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-5-2013 14:10:00', 'SEA', 'Seattle', 'Mariners', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-5-2013 19:05:00', 'BOS', 'Boston', 'Red Sox', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-5-2013 19:05:00', 'CHW', 'Chicago', 'White Sox', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-5-2013 19:10:00', 'STL', 'St. Louis', 'Cardinals', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-5-2013 22:05:00', 'HOU', 'Houston', 'Astros', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-5-2013 22:05:00', 'TB', 'Tampa Bay', 'Rays', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-5-2013 22:15:00', 'ARI', 'Arizona', 'Diamondbacks', 'SF', 'San Francisco', 'Giants');






--September 6, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-6-2013 14:20:00', 'MIL', 'Milwaukee', 'Brewers', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-6-2013 19:05:00', 'ATL', 'Atlanta', 'Braves', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-6-2013 19:05:00', 'BOS', 'Boston', 'Red Sox', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-6-2013 19:05:00', 'CHW', 'Chicago', 'White Sox', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-6-2013 19:05:00', 'NYM', 'New York', 'Mets', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-6-2013 19:10:00', 'LAD', 'Los Angeles', 'Dodgers', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-6-2013 19:10:00', 'WSH', 'Washington D.C.', 'Nationals', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-6-2013 20:10:00', 'DET', 'Detroit', 'Tigers', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-6-2013 20:10:00', 'TOR', 'Toronto', 'Blue Jays', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-6-2013 20:15:00', 'PIT', 'Pittsburgh', 'Pirates', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-6-2013 22:05:00', 'HOU', 'Houston', 'Astros', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-6-2013 22:05:00', 'TEX', 'Texas', 'Rangers', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-6-2013 22:10:00', 'COL', 'Colorado', 'Rockies', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-6-2013 22:10:00', 'TB', 'Tampa Bay', 'Rays', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-6-2013 22:15:00', 'ARI', 'Arizona', 'Diamondbacks', 'SF', 'San Francisco', 'Giants');






--September 7, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-7-2013 13:05:00', 'BOS', 'Boston', 'Red Sox', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-7-2013 13:05:00', 'LAD', 'Los Angeles', 'Dodgers', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-7-2013 13:05:00', 'MIL', 'Milwaukee', 'Brewers', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-7-2013 16:05:00', 'HOU', 'Houston', 'Astros', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-7-2013 18:05:00', 'NYM', 'New York', 'Mets', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-7-2013 19:05:00', 'ATL', 'Atlanta', 'Braves', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-7-2013 19:05:00', 'CHW', 'Chicago', 'White Sox', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-7-2013 19:10:00', 'DET', 'Detroit', 'Tigers', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-7-2013 19:10:00', 'TOR', 'Toronto', 'Blue Jays', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-7-2013 19:10:00', 'WSH', 'Washington D.C.', 'Nationals', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-7-2013 19:15:00', 'PIT', 'Pittsburgh', 'Pirates', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-7-2013 20:40:00', 'COL', 'Colorado', 'Rockies', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-7-2013 21:05:00', 'ARI', 'Arizona', 'Diamondbacks', 'SF', 'San Francisco', 'Giants');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-7-2013 21:05:00', 'TEX', 'Texas', 'Rangers', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-7-2013 21:10:00', 'TB', 'Tampa Bay', 'Rays', 'SEA', 'Seattle', 'Mariners');






--September 8, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-8-2013 00:00:00', 'BOS', 'Boston', 'Red Sox', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-8-2013 00:00:00', 'TEX', 'Texas', 'Rangers', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-8-2013 13:05:00', 'NYM', 'New York', 'Mets', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-8-2013 13:10:00', 'LAD', 'Los Angeles', 'Dodgers', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-8-2013 13:10:00', 'WSH', 'Washington D.C.', 'Nationals', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-8-2013 13:35:00', 'ATL', 'Atlanta', 'Braves', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-8-2013 13:35:00', 'CHW', 'Chicago', 'White Sox', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-8-2013 14:10:00', 'DET', 'Detroit', 'Tigers', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-8-2013 14:10:00', 'TOR', 'Toronto', 'Blue Jays', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-8-2013 14:15:00', 'PIT', 'Pittsburgh', 'Pirates', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-8-2013 14:20:00', 'MIL', 'Milwaukee', 'Brewers', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-8-2013 16:05:00', 'ARI', 'Arizona', 'Diamondbacks', 'SF', 'San Francisco', 'Giants');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-8-2013 16:05:00', 'HOU', 'Houston', 'Astros', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-8-2013 16:10:00', 'COL', 'Colorado', 'Rockies', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-8-2013 16:10:00', 'TB', 'Tampa Bay', 'Rays', 'SEA', 'Seattle', 'Mariners');






--September 9, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-9-2013 19:05:00', 'KC', 'Kansas City', 'Royals', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-9-2013 19:05:00', 'NYY', 'New York', 'Yankees', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-9-2013 19:10:00', 'LAA', 'Anaheim', 'Angels', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-9-2013 19:10:00', 'ATL', 'Atlanta', 'Braves', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-9-2013 19:10:00', 'CHC', 'Chicago', 'Cubs', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-9-2013 19:10:00', 'WSH', 'Washington D.C.', 'Nationals', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-9-2013 20:05:00', 'PIT', 'Pittsburgh', 'Pirates', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-9-2013 20:10:00', 'DET', 'Detroit', 'Tigers', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-9-2013 22:10:00', 'ARI', 'Arizona', 'Diamondbacks', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-9-2013 22:10:00', 'HOU', 'Houston', 'Astros', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-9-2013 22:15:00', 'COL', 'Colorado', 'Rockies', 'SF', 'San Francisco', 'Giants');






--September 10, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-10-2013 19:05:00', 'KC', 'Kansas City', 'Royals', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-10-2013 19:05:00', 'NYY', 'New York', 'Yankees', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-10-2013 19:05:00', 'SD', 'San Diego', 'Padres', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-10-2013 19:07:00', 'LAA', 'Anaheim', 'Angels', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-10-2013 19:10:00', 'ATL', 'Atlanta', 'Braves', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-10-2013 19:10:00', 'BOS', 'Boston', 'Red Sox', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-10-2013 19:10:00', 'CHC', 'Chicago', 'Cubs', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-10-2013 19:10:00', 'WSH', 'Washington D.C.', 'Nationals', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-10-2013 20:05:00', 'PIT', 'Pittsburgh', 'Pirates', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-10-2013 20:10:00', 'DET', 'Detroit', 'Tigers', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-10-2013 20:10:00', 'OAK', 'Oakland', 'Athletics', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-10-2013 20:15:00', 'MIL', 'Milwaukee', 'Brewers', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-10-2013 22:10:00', 'ARI', 'Arizona', 'Diamondbacks', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-10-2013 22:10:00', 'HOU', 'Houston', 'Astros', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-10-2013 22:15:00', 'COL', 'Colorado', 'Rockies', 'SF', 'San Francisco', 'Giants');






--September 11, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-11-2013 12:05:00', 'KC', 'Kansas City', 'Royals', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-11-2013 12:35:00', 'CHC', 'Chicago', 'Cubs', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-11-2013 14:05:00', 'PIT', 'Pittsburgh', 'Pirates', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-11-2013 15:45:00', 'COL', 'Colorado', 'Rockies', 'SF', 'San Francisco', 'Giants');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-11-2013 19:05:00', 'NYY', 'New York', 'Yankees', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-11-2013 19:05:00', 'SD', 'San Diego', 'Padres', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-11-2013 19:07:00', 'LAA', 'Anaheim', 'Angels', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-11-2013 19:10:00', 'ATL', 'Atlanta', 'Braves', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-11-2013 19:10:00', 'BOS', 'Boston', 'Red Sox', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-11-2013 19:10:00', 'WSH', 'Washington D.C.', 'Nationals', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-11-2013 20:10:00', 'DET', 'Detroit', 'Tigers', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-11-2013 20:10:00', 'OAK', 'Oakland', 'Athletics', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-11-2013 20:15:00', 'MIL', 'Milwaukee', 'Brewers', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-11-2013 22:10:00', 'ARI', 'Arizona', 'Diamondbacks', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-11-2013 22:10:00', 'HOU', 'Houston', 'Astros', 'SEA', 'Seattle', 'Mariners');






--September 12, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-12-2013 12:40:00', 'ATL', 'Atlanta', 'Braves', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-12-2013 13:10:00', 'OAK', 'Oakland', 'Athletics', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-12-2013 13:10:00', 'WSH', 'Washington D.C.', 'Nationals', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-12-2013 19:05:00', 'CHC', 'Chicago', 'Cubs', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-12-2013 19:05:00', 'NYY', 'New York', 'Yankees', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-12-2013 19:05:00', 'SD', 'San Diego', 'Padres', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-12-2013 19:07:00', 'LAA', 'Anaheim', 'Angels', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-12-2013 19:10:00', 'BOS', 'Boston', 'Red Sox', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-12-2013 20:10:00', 'CLE', 'Cleveland', 'Indians', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-12-2013 20:15:00', 'MIL', 'Milwaukee', 'Brewers', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-12-2013 22:10:00', 'SF', 'San Francisco', 'Giants', 'LAD', 'Los Angeles', 'Dodgers');






--September 13, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-13-2013 14:10:00', 'CLE', 'Cleveland', 'Indians', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-13-2013 19:05:00', 'CHC', 'Chicago', 'Cubs', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-13-2013 19:05:00', 'PHI', 'Philadelphia', 'Phillies', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-13-2013 19:07:00', 'BAL', 'Baltimore', 'Orioles', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-13-2013 19:08:00', 'KC', 'Kansas City', 'Royals', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-13-2013 19:10:00', 'MIA', 'Miami', 'Marlins', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-13-2013 19:10:00', 'NYY', 'New York', 'Yankees', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-13-2013 19:30:00', 'SD', 'San Diego', 'Padres', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-13-2013 20:05:00', 'OAK', 'Oakland', 'Athletics', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-13-2013 20:10:00', 'LAA', 'Anaheim', 'Angels', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-13-2013 20:10:00', 'CIN', 'Cincinatti', 'Reds', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-13-2013 20:10:00', 'TB', 'Tampa Bay', 'Rays', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-13-2013 20:15:00', 'SEA', 'Seattle', 'Mariners', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-13-2013 21:40:00', 'COL', 'Colorado', 'Rockies', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-13-2013 22:10:00', 'SF', 'San Francisco', 'Giants', 'LAD', 'Los Angeles', 'Dodgers');






--September 14, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-14-2013 13:05:00', 'CIN', 'Cincinatti', 'Reds', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-14-2013 13:05:00', 'NYY', 'New York', 'Yankees', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-14-2013 13:05:00', 'OAK', 'Oakland', 'Athletics', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-14-2013 13:07:00', 'BAL', 'Baltimore', 'Orioles', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-14-2013 16:10:00', 'MIA', 'Miami', 'Marlins', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-14-2013 19:05:00', 'CHC', 'Chicago', 'Cubs', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-14-2013 19:05:00', 'PHI', 'Philadelphia', 'Phillies', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-14-2013 19:08:00', 'KC', 'Kansas City', 'Royals', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-14-2013 19:10:00', 'LAA', 'Anaheim', 'Angels', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-14-2013 19:10:00', 'CLE', 'Cleveland', 'Indians', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-14-2013 19:10:00', 'SD', 'San Diego', 'Padres', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-14-2013 19:10:00', 'TB', 'Tampa Bay', 'Rays', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-14-2013 19:15:00', 'SEA', 'Seattle', 'Mariners', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-14-2013 20:10:00', 'COL', 'Colorado', 'Rockies', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-14-2013 21:10:00', 'SF', 'San Francisco', 'Giants', 'LAD', 'Los Angeles', 'Dodgers');






--September 15, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-15-2013 00:00:00', 'NYY', 'New York', 'Yankees', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-15-2013 00:00:00', 'SF', 'San Francisco', 'Giants', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-15-2013 13:07:00', 'BAL', 'Baltimore', 'Orioles', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-15-2013 13:08:00', 'KC', 'Kansas City', 'Royals', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-15-2013 13:10:00', 'MIA', 'Miami', 'Marlins', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-15-2013 13:35:00', 'CHC', 'Chicago', 'Cubs', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-15-2013 13:35:00', 'PHI', 'Philadelphia', 'Phillies', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-15-2013 13:35:00', 'SD', 'San Diego', 'Padres', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-15-2013 14:10:00', 'LAA', 'Anaheim', 'Angels', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-15-2013 14:10:00', 'CIN', 'Cincinatti', 'Reds', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-15-2013 14:10:00', 'CLE', 'Cleveland', 'Indians', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-15-2013 14:10:00', 'TB', 'Tampa Bay', 'Rays', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-15-2013 14:15:00', 'SEA', 'Seattle', 'Mariners', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-15-2013 15:05:00', 'OAK', 'Oakland', 'Athletics', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-15-2013 16:10:00', 'COL', 'Colorado', 'Rockies', 'ARI', 'Arizona', 'Diamondbacks');






--September 16, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-16-2013 19:05:00', 'ATL', 'Atlanta', 'Braves', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-16-2013 19:05:00', 'MIA', 'Miami', 'Marlins', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-16-2013 19:05:00', 'SD', 'San Diego', 'Padres', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-16-2013 19:08:00', 'SEA', 'Seattle', 'Mariners', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-16-2013 19:10:00', 'TEX', 'Texas', 'Rangers', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-16-2013 20:10:00', 'CHC', 'Chicago', 'Cubs', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-16-2013 20:10:00', 'CIN', 'Cincinatti', 'Reds', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-16-2013 20:10:00', 'CLE', 'Cleveland', 'Indians', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-16-2013 20:10:00', 'MIN', 'Minnesota', 'Twins', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-16-2013 20:40:00', 'STL', 'St. Louis', 'Cardinals', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-16-2013 21:40:00', 'LAD', 'Los Angeles', 'Dodgers', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-16-2013 22:05:00', 'LAA', 'Anaheim', 'Angels', 'OAK', 'Oakland', 'Athletics');






--September 17, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-17-2013 19:05:00', 'ATL', 'Atlanta', 'Braves', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-17-2013 19:05:00', 'MIA', 'Miami', 'Marlins', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-17-2013 19:05:00', 'SD', 'San Diego', 'Padres', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-17-2013 19:07:00', 'NYY', 'New York', 'Yankees', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-17-2013 19:08:00', 'SEA', 'Seattle', 'Mariners', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-17-2013 19:10:00', 'BAL', 'Baltimore', 'Orioles', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-17-2013 19:10:00', 'SF', 'San Francisco', 'Giants', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-17-2013 19:10:00', 'TEX', 'Texas', 'Rangers', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-17-2013 20:10:00', 'CHC', 'Chicago', 'Cubs', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-17-2013 20:10:00', 'CIN', 'Cincinatti', 'Reds', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-17-2013 20:10:00', 'CLE', 'Cleveland', 'Indians', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-17-2013 20:10:00', 'MIN', 'Minnesota', 'Twins', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-17-2013 20:40:00', 'STL', 'St. Louis', 'Cardinals', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-17-2013 21:40:00', 'LAD', 'Los Angeles', 'Dodgers', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-17-2013 22:05:00', 'LAA', 'Anaheim', 'Angels', 'OAK', 'Oakland', 'Athletics');






--September 18, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-18-2013 14:10:00', 'MIN', 'Minnesota', 'Twins', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-18-2013 15:35:00', 'LAA', 'Anaheim', 'Angels', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-18-2013 19:05:00', 'ATL', 'Atlanta', 'Braves', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-18-2013 19:05:00', 'MIA', 'Miami', 'Marlins', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-18-2013 19:05:00', 'SD', 'San Diego', 'Padres', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-18-2013 19:07:00', 'NYY', 'New York', 'Yankees', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-18-2013 19:08:00', 'SEA', 'Seattle', 'Mariners', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-18-2013 19:10:00', 'BAL', 'Baltimore', 'Orioles', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-18-2013 19:10:00', 'SF', 'San Francisco', 'Giants', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-18-2013 19:10:00', 'TEX', 'Texas', 'Rangers', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-18-2013 20:10:00', 'CHC', 'Chicago', 'Cubs', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-18-2013 20:10:00', 'CIN', 'Cincinatti', 'Reds', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-18-2013 20:10:00', 'CLE', 'Cleveland', 'Indians', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-18-2013 20:40:00', 'STL', 'St. Louis', 'Cardinals', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-18-2013 21:40:00', 'LAD', 'Los Angeles', 'Dodgers', 'ARI', 'Arizona', 'Diamondbacks');






--September 19, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-19-2013 12:35:00', 'SD', 'San Diego', 'Padres', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-19-2013 13:08:00', 'SEA', 'Seattle', 'Mariners', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-19-2013 13:10:00', 'SF', 'San Francisco', 'Giants', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-19-2013 14:10:00', 'CHC', 'Chicago', 'Cubs', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-19-2013 15:10:00', 'STL', 'St. Louis', 'Cardinals', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-19-2013 15:40:00', 'LAD', 'Los Angeles', 'Dodgers', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-19-2013 19:05:00', 'HOU', 'Houston', 'Astros', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-19-2013 19:05:00', 'MIA', 'Miami', 'Marlins', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-19-2013 19:07:00', 'NYY', 'New York', 'Yankees', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-19-2013 19:10:00', 'BAL', 'Baltimore', 'Orioles', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-19-2013 19:10:00', 'TEX', 'Texas', 'Rangers', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-19-2013 22:05:00', 'MIN', 'Minnesota', 'Twins', 'OAK', 'Oakland', 'Athletics');






--September 20, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-20-2013 14:20:00', 'ATL', 'Atlanta', 'Braves', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-20-2013 19:05:00', 'CIN', 'Cincinatti', 'Reds', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-20-2013 19:05:00', 'HOU', 'Houston', 'Astros', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-20-2013 19:05:00', 'MIA', 'Miami', 'Marlins', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-20-2013 19:05:00', 'NYM', 'New York', 'Mets', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-20-2013 19:05:00', 'SF', 'San Francisco', 'Giants', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-20-2013 19:08:00', 'CHW', 'Chicago', 'White Sox', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-20-2013 19:10:00', 'BAL', 'Baltimore', 'Orioles', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-20-2013 19:10:00', 'TOR', 'Toronto', 'Blue Jays', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-20-2013 20:10:00', 'ARI', 'Arizona', 'Diamondbacks', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-20-2013 20:10:00', 'STL', 'St. Louis', 'Cardinals', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-20-2013 20:10:00', 'TEX', 'Texas', 'Rangers', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-20-2013 22:05:00', 'MIN', 'Minnesota', 'Twins', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-20-2013 22:05:00', 'SEA', 'Seattle', 'Mariners', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-20-2013 22:10:00', 'LAD', 'Los Angeles', 'Dodgers', 'SD', 'San Diego', 'Padres');






--September 21, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-21-2013 00:00:00', 'SF', 'San Francisco', 'Giants', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-21-2013 16:05:00', 'ATL', 'Atlanta', 'Braves', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-21-2013 16:05:00', 'MIN', 'Minnesota', 'Twins', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-21-2013 18:05:00', 'HOU', 'Houston', 'Astros', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-21-2013 19:05:00', 'CIN', 'Cincinatti', 'Reds', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-21-2013 19:05:00', 'MIA', 'Miami', 'Marlins', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-21-2013 19:05:00', 'NYM', 'New York', 'Mets', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-21-2013 19:08:00', 'CHW', 'Chicago', 'White Sox', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-21-2013 19:10:00', 'BAL', 'Baltimore', 'Orioles', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-21-2013 19:10:00', 'STL', 'St. Louis', 'Cardinals', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-21-2013 19:10:00', 'TEX', 'Texas', 'Rangers', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-21-2013 19:10:00', 'TOR', 'Toronto', 'Blue Jays', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-21-2013 20:10:00', 'ARI', 'Arizona', 'Diamondbacks', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-21-2013 20:40:00', 'LAD', 'Los Angeles', 'Dodgers', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-21-2013 21:05:00', 'SEA', 'Seattle', 'Mariners', 'LAA', 'Anaheim', 'Angels');






--September 22, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-22-2013 13:05:00', 'HOU', 'Houston', 'Astros', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-22-2013 13:05:00', 'SF', 'San Francisco', 'Giants', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-22-2013 13:08:00', 'CHW', 'Chicago', 'White Sox', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-22-2013 13:35:00', 'CIN', 'Cincinatti', 'Reds', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-22-2013 13:35:00', 'MIA', 'Miami', 'Marlins', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-22-2013 13:35:00', 'NYM', 'New York', 'Mets', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-22-2013 13:35:00', 'TOR', 'Toronto', 'Blue Jays', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-22-2013 13:40:00', 'BAL', 'Baltimore', 'Orioles', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-22-2013 14:10:00', 'STL', 'St. Louis', 'Cardinals', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-22-2013 14:10:00', 'TEX', 'Texas', 'Rangers', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-22-2013 14:20:00', 'ATL', 'Atlanta', 'Braves', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-22-2013 15:35:00', 'SEA', 'Seattle', 'Mariners', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-22-2013 16:05:00', 'MIN', 'Minnesota', 'Twins', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-22-2013 16:10:00', 'ARI', 'Arizona', 'Diamondbacks', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-22-2013 16:10:00', 'LAD', 'Los Angeles', 'Dodgers', 'SD', 'San Diego', 'Padres');






--September 23, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-23-2013 15:10:00', 'BAL', 'Baltimore', 'Orioles', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-23-2013 19:10:00', 'MIL', 'Milwaukee', 'Brewers', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-23-2013 19:10:00', 'NYM', 'New York', 'Mets', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-23-2013 19:10:00', 'PHI', 'Philadelphia', 'Phillies', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-23-2013 20:05:00', 'HOU', 'Houston', 'Astros', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-23-2013 20:05:00', 'PIT', 'Pittsburgh', 'Pirates', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-23-2013 20:10:00', 'DET', 'Detroit', 'Tigers', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-23-2013 20:15:00', 'WSH', 'Washington D.C.', 'Nationals', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-23-2013 22:05:00', 'OAK', 'Oakland', 'Athletics', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-23-2013 22:10:00', 'ARI', 'Arizona', 'Diamondbacks', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-23-2013 22:10:00', 'KC', 'Kansas City', 'Royals', 'SEA', 'Seattle', 'Mariners');






--September 24, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-24-2013 19:05:00', 'CHW', 'Chicago', 'White Sox', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-24-2013 19:05:00', 'TB', 'Tampa Bay', 'Rays', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-24-2013 19:05:00', 'TOR', 'Toronto', 'Blue Jays', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-24-2013 19:10:00', 'MIL', 'Milwaukee', 'Brewers', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-24-2013 19:10:00', 'NYM', 'New York', 'Mets', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-24-2013 19:10:00', 'PHI', 'Philadelphia', 'Phillies', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-24-2013 20:05:00', 'HOU', 'Houston', 'Astros', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-24-2013 20:05:00', 'PIT', 'Pittsburgh', 'Pirates', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-24-2013 20:10:00', 'DET', 'Detroit', 'Tigers', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-24-2013 20:15:00', 'WSH', 'Washington D.C.', 'Nationals', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-24-2013 20:40:00', 'BOS', 'Boston', 'Red Sox', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-24-2013 22:05:00', 'OAK', 'Oakland', 'Athletics', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-24-2013 22:10:00', 'ARI', 'Arizona', 'Diamondbacks', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-24-2013 22:10:00', 'KC', 'Kansas City', 'Royals', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-24-2013 22:15:00', 'LAD', 'Los Angeles', 'Dodgers', 'SF', 'San Francisco', 'Giants');






--September 25, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-25-2013 12:35:00', 'NYM', 'New York', 'Mets', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-25-2013 13:45:00', 'WSH', 'Washington D.C.', 'Nationals', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-25-2013 14:20:00', 'PIT', 'Pittsburgh', 'Pirates', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-25-2013 15:35:00', 'OAK', 'Oakland', 'Athletics', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-25-2013 19:05:00', 'CHW', 'Chicago', 'White Sox', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-25-2013 19:05:00', 'TB', 'Tampa Bay', 'Rays', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-25-2013 19:05:00', 'TOR', 'Toronto', 'Blue Jays', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-25-2013 19:10:00', 'MIL', 'Milwaukee', 'Brewers', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-25-2013 19:10:00', 'PHI', 'Philadelphia', 'Phillies', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-25-2013 20:05:00', 'HOU', 'Houston', 'Astros', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-25-2013 20:10:00', 'DET', 'Detroit', 'Tigers', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-25-2013 20:40:00', 'BOS', 'Boston', 'Red Sox', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-25-2013 22:10:00', 'ARI', 'Arizona', 'Diamondbacks', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-25-2013 22:10:00', 'KC', 'Kansas City', 'Royals', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-25-2013 22:15:00', 'LAD', 'Los Angeles', 'Dodgers', 'SF', 'San Francisco', 'Giants');






--September 26, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-26-2013 18:40:00', 'ARI', 'Arizona', 'Diamondbacks', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-26-2013 19:05:00', 'TB', 'Tampa Bay', 'Rays', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-26-2013 19:05:00', 'TOR', 'Toronto', 'Blue Jays', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-26-2013 19:10:00', 'MIL', 'Milwaukee', 'Brewers', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-26-2013 19:10:00', 'PHI', 'Philadelphia', 'Phillies', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-26-2013 20:05:00', 'LAA', 'Anaheim', 'Angels', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-26-2013 20:10:00', 'CLE', 'Cleveland', 'Indians', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-26-2013 20:10:00', 'KC', 'Kansas City', 'Royals', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-26-2013 22:15:00', 'LAD', 'Los Angeles', 'Dodgers', 'SF', 'San Francisco', 'Giants');






--September 27, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-27-2013 19:05:00', 'BOS', 'Boston', 'Red Sox', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-27-2013 19:07:00', 'TB', 'Tampa Bay', 'Rays', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-27-2013 19:10:00', 'DET', 'Detroit', 'Tigers', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-27-2013 19:10:00', 'MIL', 'Milwaukee', 'Brewers', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-27-2013 19:10:00', 'PIT', 'Pittsburgh', 'Pirates', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-27-2013 19:30:00', 'PHI', 'Philadelphia', 'Phillies', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-27-2013 20:05:00', 'LAA', 'Anaheim', 'Angels', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-27-2013 20:10:00', 'CLE', 'Cleveland', 'Indians', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-27-2013 20:10:00', 'KC', 'Kansas City', 'Royals', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-27-2013 20:10:00', 'NYY', 'New York', 'Yankees', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-27-2013 20:15:00', 'CHC', 'Chicago', 'Cubs', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-27-2013 21:40:00', 'WSH', 'Washington D.C.', 'Nationals', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-27-2013 22:10:00', 'COL', 'Colorado', 'Rockies', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-27-2013 22:10:00', 'OAK', 'Oakland', 'Athletics', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-27-2013 22:15:00', 'SD', 'San Diego', 'Padres', 'SF', 'San Francisco', 'Giants');





--September 28, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-28-2013 00:00:00', 'COL', 'Colorado', 'Rockies', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-28-2013 13:07:00', 'TB', 'Tampa Bay', 'Rays', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-28-2013 16:05:00', 'SD', 'San Diego', 'Padres', 'SF', 'San Francisco', 'Giants');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-28-2013 16:10:00', 'CLE', 'Cleveland', 'Indians', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-28-2013 16:10:00', 'MIL', 'Milwaukee', 'Brewers', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-28-2013 16:10:00', 'OAK', 'Oakland', 'Athletics', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-28-2013 16:10:00', 'PIT', 'Pittsburgh', 'Pirates', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-28-2013 19:05:00', 'BOS', 'Boston', 'Red Sox', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-28-2013 19:10:00', 'DET', 'Detroit', 'Tigers', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-28-2013 19:10:00', 'KC', 'Kansas City', 'Royals', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-28-2013 19:10:00', 'NYY', 'New York', 'Yankees', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-28-2013 19:10:00', 'PHI', 'Philadelphia', 'Phillies', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-28-2013 19:15:00', 'CHC', 'Chicago', 'Cubs', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-28-2013 20:05:00', 'LAA', 'Anaheim', 'Angels', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-28-2013 20:10:00', 'WSH', 'Washington D.C.', 'Nationals', 'ARI', 'Arizona', 'Diamondbacks');






--September 29, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-29-2013 13:07:00', 'TB', 'Tampa Bay', 'Rays', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-29-2013 13:10:00', 'DET', 'Detroit', 'Tigers', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-29-2013 13:10:00', 'MIL', 'Milwaukee', 'Brewers', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-29-2013 13:10:00', 'PIT', 'Pittsburgh', 'Pirates', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-29-2013 13:35:00', 'BOS', 'Boston', 'Red Sox', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-29-2013 13:35:00', 'PHI', 'Philadelphia', 'Phillies', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-29-2013 14:10:00', 'CLE', 'Cleveland', 'Indians', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-29-2013 14:10:00', 'KC', 'Kansas City', 'Royals', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-29-2013 14:10:00', 'NYY', 'New York', 'Yankees', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-29-2013 14:15:00', 'CHC', 'Chicago', 'Cubs', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-29-2013 15:05:00', 'LAA', 'Anaheim', 'Angels', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-29-2013 16:05:00', 'SD', 'San Diego', 'Padres', 'SF', 'San Francisco', 'Giants');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-29-2013 16:10:00', 'COL', 'Colorado', 'Rockies', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-29-2013 16:10:00', 'OAK', 'Oakland', 'Athletics', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '9-29-2013 16:10:00', 'WSH', 'Washington D.C.', 'Nationals', 'ARI', 'Arizona', 'Diamondbacks');






--September 30, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', '', '', '', '', '', '');
