--March 31, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES('3-31-2013', 'TEX' 'Texas', 'Rangers', 'HOU' 'Houston', 'Astros');

--April 1, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-1-2013', 'BOS', 'Boston', 'Red Sox', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-1-2013', 'MIA', 'Miami', 'Marlins', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-1-2013', 'SD', 'San Diego', 'Padres', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-1-2013', 'CHC', 'Chicago', 'Cubs', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-1-2013', 'COL', 'Colorado', 'Rockies', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-1-2013', 'LAA', 'Anaheim', 'Angels', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-1-2013', 'DET', 'Detroit', 'Tigers', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-1-2013', 'KC', 'Kansas City', 'Royals', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-1-2013', 'SF', 'San Francisco', 'Giants', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-1-2013', 'PHI', 'Philadelphia', 'Phillies', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-1-2013', 'SEA', 'Seattle', 'Mariners', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-1-2013', 'STL', 'St. Louis', 'Cardinals', 'ARI', 'Arizona', 'Diamondbacks');




--April 2, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-2-2013', 'BAL', 'Baltimore', 'Orioles', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-2-2013', 'CLE', 'Cleveland', 'Indians', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-2-2013', 'COL', 'Colorado', 'Rockies', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-2-2013', 'TEX', 'Texas', 'Rangers', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-2-2013', 'STL', 'St. Louis', 'Cardinals', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-2-2013', 'SEA', 'Seattle', 'Mariners', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-2-2013', 'SF', 'San Francisco', 'Giants', 'LAD', 'Los Angeles', 'Dodgers');




--April 3, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-3-2013', 'KC', 'Kansas City', 'Royals', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-3-2013', 'TEX', 'Texas', 'Rangers', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-3-2013', 'DET', 'Detroit', 'Tigers', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-3-2013', 'BOS', 'Boston', 'Red Sox', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-3-2013', 'CHC', 'Chicago', 'Cubs', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-3-2013', 'MIA', 'Miami', 'Marlins', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-3-2013', 'CLE', 'Cleveland', 'Indians', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-3-2013', 'LAA', 'Anaheim', 'Angels', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-3-2013', 'BAL', 'Baltimore', 'Orioles', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-3-2013', 'PHI', 'Philadelphia', 'Phillies', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-3-2013', 'SD', 'San Diego', 'Padres', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-3-2013', 'COL', 'Colorado', 'Rockies', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-3-2013', 'STL', 'St. Louis', 'Cardinals', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-3-2013', 'SEA', 'Seattle', 'Mariners', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-3-2013', 'SF', 'San Francisco', 'Giants', 'LAD', 'Los Angeles', 'Dodgers');




--April 4, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-4-2013', 'LAA', 'Anaheim', 'Angels', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-4-2013', 'CHC', 'Chicago', 'Cubs', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-4-2013', 'DET', 'Detroit', 'Tigers', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-4-2013', 'SD', 'San Diego', 'Padres', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-4-2013', 'KC', 'Kansas City', 'Royals', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-4-2013', 'BAL', 'Baltimore', 'Orioles', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-4-2013', 'SEA', 'Seattle', 'Mariners', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-4-2013', 'MIA', 'Miami', 'Marlins', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-4-2013', 'BOS', 'Boston', 'Red Sox', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-4-2013', 'CLE', 'Cleveland', 'Indians', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-4-2013', 'PHI', 'Philadelphia', 'Phillies', 'ATL', 'Atlanta', 'Braves');




--April 5, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-5-2013', 'NYY', 'New York', 'Yankees', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-5-2013', 'LAA', 'Anaheim', 'Angels', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-5-2013', 'MIN', 'Minnesota', 'Twins', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-5-2013', 'KC', 'Kansas City', 'Royals', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-5-2013', 'SD', 'San Diego', 'Padres', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-5-2013', 'STL', 'St. Louis', 'Cardinals', 'SF', 'San Francisco', 'Giants');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-5-2013', 'BOS', 'Boston', 'Red Sox', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-5-2013', 'CLE', 'Cleveland', 'Indians', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-5-2013', 'MIA', 'Miami', 'Marlins', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-5-2013', 'WSH', 'Washington D.C.', 'Nationals', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-5-2013', 'CHC', 'Chicago', 'Cubs', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-5-2013', 'ARI', 'Arizona', 'Diamondbacks', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-5-2013', 'OAK', 'Oakland', 'Athletics', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-5-2013', 'SEA', 'Seattle', 'Mariners', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-5-2013', 'PIT', 'Pittsburgh', 'Pirates', 'LAD', 'Los Angeles', 'Dodgers');





--April 6, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-6-2013', 'BOS', 'Boston', 'Red Sox', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-6-2013', 'MIA', 'Miami', 'Marlins', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-6-2013', 'SEA', 'Seattle', 'Mariners', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-6-2013', 'WSH', 'Washington D.C.', 'Nationals', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-6-2013', 'LAA', 'Anaheim', 'Angels', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-6-2013', 'NYY', 'New York', 'Yankees', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-6-2013', 'STL', 'St. Louis', 'Cardinals', 'SF', 'San Francisco', 'Giants');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-6-2013', 'KC', 'Kansas City', 'Royals', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-6-2013', 'MIN', 'Minnesota', 'Twins', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-6-2013', 'ARI', 'Arizona', 'Diamondbacks', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-6-2013', 'CHC', 'Chicago', 'Cubs', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-6-2013', 'CLE', 'Cleveland', 'Indians', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-6-2013', 'OAK', 'Oakland', 'Athletics', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-6-2013', 'SD', 'San Diego', 'Padres', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-6-2013', 'PIT', 'Pittsburgh', 'Pirates', 'LAD', 'Los Angeles', 'Dodgers');






--April 7, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-7-2013', 'BOS', 'Boston', 'Red Sox', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-7-2013', 'NYY', 'New York', 'Yankees', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-7-2013', 'MIA', 'Miami', 'Marlins', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-7-2013', 'WSH', 'Washington D.C.', 'Nationals', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-7-2013', 'CHC', 'Chicago', 'Cubs', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-7-2013', 'KC', 'Kansas City', 'Royals', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-7-2013', 'MIN', 'Minnesota', 'Twins', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-7-2013', 'CLE', 'Cleveland', 'Indians', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-7-2013', 'ARI', 'Arizona', 'Diamondbacks', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-7-2013', 'OAK', 'Oakland', 'Athletics', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-7-2013', 'SEA', 'Seattle', 'Mariners', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-7-2013', 'PIT', 'Pittsburgh', 'Pirates', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-7-2013', 'SD', 'San Diego', 'Padres', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-7-2013', 'STL', 'St. Louis', 'Cardinals', 'SF', 'San Francisco', 'Giants');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-7-2013', 'LAA', 'Anaheim', 'Angels', 'TEX', 'Texas', 'Rangers');






--April 8, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-8-2013', 'BAL', 'Baltimore', 'Orioles', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-8-2013', 'MIL', 'Milwaukee', 'Brewers', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-8-2013', 'NYY', 'New York', 'Yankees', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-8-2013', 'MIN', 'Minnesota', 'Twins', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-8-2013', 'CIN', 'Cincinatti', 'Reds', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-8-2013', 'NYM', 'New York', 'Mets', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-8-2013', 'ATL', 'Atlanta', 'Braves', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-8-2013', 'TB', 'Tampa Bay', 'Rays', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-8-2013', 'PIT', 'Pittsburgh', 'Pirates', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-8-2013', 'HOU', 'Houston', 'Astros', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-8-2013', 'COL', 'Colorado', 'Rockies', 'SF', 'San Francisco', 'Giants');






--April 9, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-9-2013', 'TOR', 'Toronto', 'Blue Jays', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-9-2013', 'LAD', 'Los Angeles', 'Dodgers', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-9-2013', 'CHW', 'Chicago', 'White Sox', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-9-2013', 'NYY', 'New York', 'Yankees', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-9-2013', 'NYM', 'New York', 'Mets', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-9-2013', 'ATL', 'Atlanta', 'Braves', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-9-2013', 'MIL', 'Milwaukee', 'Brewers', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-9-2013', 'TB', 'Tampa Bay', 'Rays', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-9-2013', 'MIN', 'Minnesota', 'Twins', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-9-2013', 'CIN', 'Cincinatti', 'Reds', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-9-2013', 'PIT', 'Pittsburgh', 'Pirates', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-9-2013', 'OAK', 'Oakland', 'Athletics', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-9-2013', 'HOU', 'Houston', 'Astros', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-9-2013', 'COL', 'Colorado', 'Rockies', 'SF', 'San Francisco', 'Giants');






--April 10, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-10-2013', 'TOR', 'Toronto', 'Blue Jays', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-10-2013', 'CIN', 'Cincinatti', 'Reds', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-10-2013', 'TB', 'Tampa Bay', 'Rays', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-10-2013', 'PIT', 'Pittsburgh', 'Pirates', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-10-2013', 'COL', 'Colorado', 'Rockies', 'SF', 'San Francisco', 'Giants');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-10-2013', 'CHW', 'Chicago', 'White Sox', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-10-2013', 'NYY', 'New York', 'Yankees', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-10-2013', 'NYM', 'New York', 'Mets', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-10-2013', 'ATL', 'Atlanta', 'Braves', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-10-2013', 'BAL', 'Baltimore', 'Orioles', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-10-2013', 'MIL', 'Milwaukee', 'Brewers', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-10-2013', 'MIN', 'Minnesota', 'Twins', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-10-2013', 'OAK', 'Oakland', 'Athletics', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-10-2013', 'HOU', 'Houston', 'Astros', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-10-2013', 'LAD', 'Los Angeles', 'Dodgers', 'SD', 'San Diego', 'Padres');





--April 11, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-11-2013', 'TOR', 'Toronto', 'Blue Jays', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-11-2013', 'SF', 'San Francisco', 'Giants', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-11-2013', 'CHW', 'Chicago', 'White Sox', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-11-2013', 'NYY', 'New York', 'Yankees', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-11-2013', 'BAL', 'Baltimore', 'Orioles', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-11-2013', 'OAK', 'Oakland', 'Athletics', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-11-2013', 'LAD', 'Los Angeles', 'Dodgers', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-11-2013', 'TEX', 'Texas', 'Rangers', 'SEA', 'Seattle', 'Mariners');






--April 12, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-12-2013', 'SF', 'San Francisco', 'Giants', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-12-2013', 'ATL', 'Atlanta', 'Braves', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-12-2013', 'BAL', 'Baltimore', 'Orioles', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-12-2013', 'CHW', 'Chicago', 'White Sox', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-12-2013', 'CIN', 'Cincinatti', 'Reds', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-12-2013', 'PHI', 'Philadelphia', 'Phillies', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-12-2013', 'TB', 'Tampa Bay', 'Rays', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-12-2013', 'NYM', 'New York', 'Mets', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-12-2013', 'TOR', 'Toronto', 'Blue Jays', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-12-2013', 'MIL', 'Milwaukee', 'Brewers', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-12-2013', 'LAD', 'Los Angeles', 'Dodgers', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-12-2013', 'DET', 'Detroit', 'Tigers', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-12-2013', 'HOU', 'Houston', 'Astros', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-12-2013', 'COL', 'Colorado', 'Rockies', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-12-2013', 'TEX', 'Texas', 'Rangers', 'SEA', 'Seattle', 'Mariners');







--April 13, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-13-2013', 'ATL', 'Atlanta', 'Braves', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-13-2013', 'SF', 'San Francisco', 'Giants', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-13-2013', 'TB', 'Tampa Bay', 'Rays', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-13-2013', 'BAL', 'Baltimore', 'Orioles', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-13-2013', 'CHW', 'Chicago', 'White Sox', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-13-2013', 'DET', 'Detroit', 'Tigers', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-13-2013', 'NYM', 'New York', 'Mets', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-13-2013', 'MIL', 'Milwaukee', 'Brewers', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-13-2013', 'CIN', 'Cincinatti', 'Reds', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-13-2013', 'PHI', 'Philadelphia', 'Phillies', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-13-2013', 'TOR', 'Toronto', 'Blue Jays', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-13-2013', 'LAD', 'Los Angeles', 'Dodgers', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-13-2013', 'COL', 'Colorado', 'Rockies', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-13-2013', 'HOU', 'Houston', 'Astros', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-13-2013', 'TEX', 'Texas', 'Rangers', 'SEA', 'Seattle', 'Mariners');






--April 14, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-14-2013', 'CHW', 'Chicago', 'White Sox', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-14-2013', 'PHI', 'Philadelphia', 'Phillies', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-14-2013', 'ATL', 'Atlanta', 'Braves', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-14-2013', 'CIN', 'Cincinatti', 'Reds', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-14-2013', 'TB', 'Tampa Bay', 'Rays', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-14-2013', 'NYM', 'New York', 'Mets', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-14-2013', 'TOR', 'Toronto', 'Blue Jays', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-14-2013', 'MIL', 'Milwaukee', 'Brewers', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-14-2013', 'SF', 'San Francisco', 'Giants', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-14-2013', 'HOU', 'Houston', 'Astros', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-14-2013', 'DET', 'Detroit', 'Tigers', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-14-2013', 'COL', 'Colorado', 'Rockies', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-14-2013', 'LAD', 'Los Angeles', 'Dodgers', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-14-2013', 'TEX', 'Texas', 'Rangers', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-14-2013', 'BAL', 'Baltimore', 'Orioles', 'NYY', 'New York', 'Yankees');






--April 15, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-15-2013', 'TB', 'Tampa Bay', 'Rays', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-15-2013', 'NYM', 'New York', 'Mets', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-15-2013', 'STL', 'St. Louis', 'Cardinals', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-15-2013', 'CHW', 'Chicago', 'White Sox', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-15-2013', 'PHI', 'Philadelphia', 'Phillies', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-15-2013', 'WSH', 'Washington D.C.', 'Nationals', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-15-2013', 'LAA', 'Anaheim', 'Angels', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-15-2013', 'HOU', 'Houston', 'Astros', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-15-2013', 'SD', 'San Diego', 'Padres', 'LAD', 'Los Angeles', 'Dodgers');





--April 16, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-16-2013', 'NYM', 'New York', 'Mets', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-16-2013', 'ARI', 'Arizona', 'Diamondbacks', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-16-2013', 'BOS', 'Boston', 'Red Sox', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-16-2013', 'STL', 'St. Louis', 'Cardinals', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-16-2013', 'TB', 'Tampa Bay', 'Rays', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-16-2013', 'CHW', 'Chicago', 'White Sox', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-16-2013', 'KC', 'Kansas City', 'Royals', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-16-2013', 'PHI', 'Philadelphia', 'Phillies', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-16-2013', 'WSH', 'Washington D.C.', 'Nationals', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-16-2013', 'TEX', 'Texas', 'Rangers', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-16-2013', 'LAA', 'Anaheim', 'Angels', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-16-2013', 'SF', 'San Francisco', 'Giants', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-16-2013', 'NYM', 'New York', 'Mets', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-16-2013', 'HOU', 'Houston', 'Astros', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-16-2013', 'DET', 'Detroit', 'Tigers', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-16-2013', 'SD', 'San Diego', 'Padres', 'LAD', 'Los Angeles', 'Dodgers');






--April 17, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-17-2013', 'KC', 'Kansas City', 'Royals', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-17-2013', 'HOU', 'Houston', 'Astros', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-17-2013', 'PHI', 'Philadelphia', 'Phillies', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-17-2013', 'ARI', 'Arizona', 'Diamondbacks', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-17-2013', 'BOS', 'Boston', 'Red Sox', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-17-2013', 'STL', 'St. Louis', 'Cardinals', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-17-2013', 'TB', 'Tampa Bay', 'Rays', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-17-2013', 'CHW', 'Chicago', 'White Sox', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-17-2013', 'PHI', 'Philadelphia', 'Phillies', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-17-2013', 'WSH', 'Washington D.C.', 'Nationals', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-17-2013', 'TEX', 'Texas', 'Rangers', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-17-2013', 'LAA', 'Anaheim', 'Angels', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-17-2013', 'SF', 'San Francisco', 'Giants', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-17-2013', 'NYM', 'New York', 'Mets', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-17-2013', 'DET', 'Detroit', 'Tigers', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-17-2013', 'SD', 'San Diego', 'Padres', 'LAD', 'Los Angeles', 'Dodgers');






--April 18, 20134-17-2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-18-2013', 'SF', 'San Francisco', 'Giants', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-18-2013', 'TEX', 'Texas', 'Rangers', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-18-2013', 'NYM', 'New York', 'Mets', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-18-2013', 'DET', 'Detroit', 'Tigers', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-18-2013', 'ARI', 'Arizona', 'Diamondbacks', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-18-2013', 'ATL', 'Atlanta', 'Braves', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-18-2013', 'BOS', 'Boston', 'Red Sox', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-18-2013', 'STL', 'St. Louis', 'Cardinals', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-18-2013', 'TB', 'Tampa Bay', 'Rays', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-18-2013', 'CHW', 'Chicago', 'White Sox', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-18-2013', 'MIA', 'Miami', 'Marlins', 'CIN', 'Cincinatti', 'Reds');






--April 19, 20134-18-2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-19-2013', 'ATL', 'Atlanta', 'Braves', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-19-2013', 'LAD', 'Los Angeles', 'Dodgers', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-19-2013', 'STL', 'St. Louis', 'Cardinals', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-19-2013', 'NYY', 'New York', 'Yankees', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-19-2013', 'KC', 'Kansas City', 'Royals', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-19-2013', 'MIA', 'Miami', 'Marlins', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-19-2013', 'OAK', 'Oakland', 'Athletics', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-19-2013', 'WSH', 'Washington D.C.', 'Nationals', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-19-2013', 'SEA', 'Seattle', 'Mariners', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-19-2013', 'CHC', 'Chicago', 'Cubs', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-19-2013', 'CLE', 'Cleveland', 'Indians', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-19-2013', 'MIN', 'Minnesota', 'Twins', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-19-2013', 'ARI', 'Arizona', 'Diamondbacks', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-19-2013', 'DET', 'Detroit', 'Tigers', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-19-2013', 'SD', 'San Diego', 'Padres', 'SF', 'San Francisco', 'Giants');






--April 20, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-20-2013', 'LAD', 'Los Angeles', 'Dodgers', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-20-2013', 'NYY', 'New York', 'Yankees', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-20-2013', 'KC', 'Kansas City', 'Royals', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-20-2013', 'MIA', 'Miami', 'Marlins', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-20-2013', 'DET', 'Detroit', 'Tigers', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-20-2013', 'MIN', 'Minnesota', 'Twins', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-20-2013', 'WSH', 'Washington D.C.', 'Nationals', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-20-2013', 'ATL', 'Atlanta', 'Braves', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-20-2013', 'LAD', 'Los Angeles', 'Dodgers', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-20-2013', 'STL', 'St. Louis', 'Cardinals', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-20-2013', 'CHC', 'Chicago', 'Cubs', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-20-2013', 'CLE', 'Cleveland', 'Indians', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-20-2013', 'OAK', 'Oakland', 'Athletics', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-20-2013', 'SEA', 'Seattle', 'Mariners', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-20-2013', 'ARI', 'Arizona', 'Diamondbacks', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-20-2013', 'SD', 'San Diego', 'Padres', 'SF', 'San Francisco', 'Giants');







--April 21, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '', 'NYY', 'New York', 'Yankees', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-21-2013', 'MIA', 'Miami', 'Marlins', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-21-2013', 'WSH', 'Washington D.C.', 'Nationals', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-21-2013', 'ATL', 'Atlanta', 'Braves', 'PIT', 'Pittsburgh', 'Pirates');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-21-2013', 'KC', 'Kansas City', 'Royals', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-21-2013', 'LAD', 'Los Angeles', 'Dodgers', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-21-2013', 'OAK', 'Oakland', 'Athletics', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-21-2013', 'CHC', 'Chicago', 'Cubs', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-21-2013', 'CLE', 'Cleveland', 'Indians', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-21-2013', 'MIN', 'Minnesota', 'Twins', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-21-2013', 'SEA', 'Seattle', 'Mariners', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-21-2013', 'DET', 'Detroit', 'Tigers', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-21-2013', 'SD', 'San Diego', 'Padres', 'SF', 'San Francisco', 'Giants');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-21-2013', 'ARI', 'Arizona', 'Diamondbacks', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-21-2013', 'KC', 'Kansas City', 'Royals', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-21-2013', 'STL', 'St. Louis', 'Cardinals', 'PHI', 'Philadelphia', 'Phillies');






--April 22, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-22-2013', 'OAK', 'Oakland', 'Athletics', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-22-2013', 'PIT', 'Pittsburgh', 'Pirates', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-22-2013', 'STL', 'St. Louis', 'Cardinals', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-22-2013', 'TOR', 'Toronto', 'Blue Jays', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-22-2013', 'CHC', 'Chicago', 'Cubs', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-22-2013', 'NYY', 'New York', 'Yankees', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-22-2013', 'CLE', 'Cleveland', 'Indians', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-22-2013', 'MIA', 'Miami', 'Marlins', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-22-2013', 'SEA', 'Seattle', 'Mariners', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-22-2013', 'ATL', 'Atlanta', 'Braves', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-22-2013', 'TEX', 'Texas', 'Rangers', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-22-2013', 'MIL', 'Milwaukee', 'Brewers', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-22-2013', 'ARI', 'Arizona', 'Diamondbacks', 'SF', 'San Francisco', 'Giants');






--April 23, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-23-2013', 'MIA', 'Miami', 'Marlins', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-23-2013', 'OAK', 'Oakland', 'Athletics', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-23-2013', 'PIT', 'Pittsburgh', 'Pirates', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-23-2013', 'STL', 'St. Louis', 'Cardinals', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-23-2013', 'TOR', 'Toronto', 'Blue Jays', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-23-2013', 'KC', 'Kansas City', 'Royals', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-23-2013', 'CHC', 'Chicago', 'Cubs', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-23-2013', 'LAD', 'Los Angeles', 'Dodgers', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-23-2013', 'NYY', 'New York', 'Yankees', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-23-2013', 'CLE', 'Cleveland', 'Indians', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-23-2013', 'MIA', 'Miami', 'Marlins', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-23-2013', 'SEA', 'Seattle', 'Mariners', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-23-2013', 'ATL', 'Atlanta', 'Braves', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-23-2013', 'TEX', 'Texas', 'Rangers', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-23-2013', 'MIL', 'Milwaukee', 'Brewers', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-23-2013', 'ARI', 'Arizona', 'Diamondbacks', 'SF', 'San Francisco', 'Giants');






--April 24, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-24-2013', 'CHC', 'Chicago', 'Cubs', 'CIN', 'Cincinatti', 'Reds');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-24-2013', 'TOR', 'Toronto', 'Blue Jays', 'BAL', 'Baltimore', 'Orioles');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-24-2013', 'STL', 'St. Louis', 'Cardinals', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-24-2013', 'CLE', 'Cleveland', 'Indians', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-24-2013', 'SEA', 'Seattle', 'Mariners', 'HOU', 'Houston', 'Astros');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-24-2013', 'ATL', 'Atlanta', 'Braves', 'COL', 'Colorado', 'Rockies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-24-2013', 'ARI', 'Arizona', 'Diamondbacks', 'SF', 'San Francisco', 'Giants');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-24-2013', 'OAK', 'Oakland', 'Athletics', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-24-2013', 'PIT', 'Pittsburgh', 'Pirates', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-24-2013', 'KC', 'Kansas City', 'Royals', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-24-2013', 'LAD', 'Los Angeles', 'Dodgers', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-24-2013', 'NYY', 'New York', 'Yankees', 'TB', 'Tampa Bay', 'Rays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-24-2013', 'TEX', 'Texas', 'Rangers', 'LAA', 'Anaheim', 'Angels');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-24-2013', 'MIL', 'Milwaukee', 'Brewers', 'SD', 'San Diego', 'Padres');






--April 25, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-25-2013', 'PIT', 'Pittsburgh', 'Pirates', 'PHI', 'Philadelphia', 'Phillies');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-25-2013', 'KC', 'Kansas City', 'Royals', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-25-2013', 'LAD', 'Los Angeles', 'Dodgers', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-25-2013', 'HOU', 'Houston', 'Astros', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-25-2013', 'CIN', 'Cincinatti', 'Reds', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-25-2013', 'TOR', 'Toronto', 'Blue Jays', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-25-2013', 'CHC', 'Chicago', 'Cubs', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-25-2013', 'TB', 'Tampa Bay', 'Rays', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-25-2013', 'TEX', 'Texas', 'Rangers', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-25-2013', 'COL', 'Colorado', 'Rockies', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-25-2013', 'BAL', 'Baltimore', 'Orioles', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-25-2013', 'LAA', 'Anaheim', 'Angels', 'SEA', 'Seattle', 'Mariners');






--April 26, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-26-2013', 'CIN', 'Cincinatti', 'Reds', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-26-2013', 'TOR', 'Toronto', 'Blue Jays', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-26-2013', 'ATL', 'Atlanta', 'Braves', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-26-2013', 'CHC', 'Chicago', 'Cubs', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-26-2013', 'HOU', 'Houston', 'Astros', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-26-2013', 'PHI', 'Philadelphia', 'Phillies', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-26-2013', 'CLE', 'Cleveland', 'Indians', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-26-2013', 'TB', 'Tampa Bay', 'Rays', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-26-2013', 'TEX', 'Texas', 'Rangers', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-26-2013', 'PIT', 'Pittsburgh', 'Pirates', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-26-2013', 'COL', 'Colorado', 'Rockies', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-26-2013', 'BAL', 'Baltimore', 'Orioles', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-26-2013', 'LAA', 'Anaheim', 'Angels', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-26-2013', 'MIL', 'Milwaukee', 'Brewers', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-26-2013', 'SF', 'San Francisco', 'Giants', 'SD', 'San Diego', 'Padres');







--April 27, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-27-2013', 'ATL', 'Atlanta', 'Braves', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-27-2013', 'CIN', 'Cincinatti', 'Reds', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-27-2013', 'PHI', 'Philadelphia', 'Phillies', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-27-2013', 'BAL', 'Baltimore', 'Orioles', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-27-2013', 'TOR', 'Toronto', 'Blue Jays', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-27-2013', 'TEX', 'Texas', 'Rangers', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-27-2013', 'PIT', 'Pittsburgh', 'Pirates', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-27-2013', 'CHC', 'Chicago', 'Cubs', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-27-2013', 'CLE', 'Cleveland', 'Indians', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-27-2013', 'HOU', 'Houston', 'Astros', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-27-2013', 'TB', 'Tampa Bay', 'Rays', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-27-2013', 'COL', 'Colorado', 'Rockies', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-27-2013', 'SF', 'San Francisco', 'Giants', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-27-2013', 'LAA', 'Anaheim', 'Angels', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-27-2013', 'MIL', 'Milwaukee', 'Brewers', 'LAD', 'Los Angeles', 'Dodgers');







--April 28, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-28-2013', 'TOR', 'Toronto', 'Blue Jays', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-28-2013', 'CHC', 'Chicago', 'Cubs', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-28-2013', 'PHI', 'Philadelphia', 'Phillies', 'NYM', 'New York', 'Mets');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-28-2013', 'CIN', 'Cincinatti', 'Reds', 'WSH', 'Washington D.C.', 'Nationals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-28-2013', 'HOU', 'Houston', 'Astros', 'BOS', 'Boston', 'Red Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-28-2013', 'CLE', 'Cleveland', 'Indians', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-28-2013', 'TB', 'Tampa Bay', 'Rays', 'CHW', 'Chicago', 'White Sox');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-28-2013', 'TEX', 'Texas', 'Rangers', 'MIN', 'Minnesota', 'Twins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-28-2013', 'PIT', 'Pittsburgh', 'Pirates', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-28-2013', 'BAL', 'Baltimore', 'Orioles', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-28-2013', 'LAA', 'Anaheim', 'Angels', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-28-2013', 'COL', 'Colorado', 'Rockies', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-28-2013', 'MIL', 'Milwaukee', 'Brewers', 'LAD', 'Los Angeles', 'Dodgers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-28-2013', 'SF', 'San Francisco', 'Giants', 'SD', 'San Diego', 'Padres');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-28-2013', 'ATL', 'Atlanta', 'Braves', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-28-2013', 'CLE', 'Cleveland', 'Indians', 'KC', 'Kansas City', 'Royals');







--April 29, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-29-2013', 'HOU', 'Houston', 'Astros', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-29-2013', 'MIN', 'Minnesota', 'Twins', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-29-2013', 'NYM', 'New York', 'Mets', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-29-2013', 'WSH', 'Washington D.C.', 'Nationals', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-29-2013', 'SD', 'San Diego', 'Padres', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-29-2013', 'CLE', 'Cleveland', 'Indians', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-29-2013', 'PIT', 'Pittsburgh', 'Pirates', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-29-2013', 'CIN', 'Cincinatti', 'Reds', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-29-2013', 'SF', 'San Francisco', 'Giants', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-29-2013', 'LAA', 'Anaheim', 'Angels', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-29-2013', 'BAL', 'Baltimore', 'Orioles', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-29-2013', 'COL', 'Colorado', 'Rockies', 'LAD', 'Los Angeles', 'Dodgers');






--April 30, 2013
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-30-2013', 'HOU', 'Houston', 'Astros', 'NYY', 'New York', 'Yankees');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-30-2013', 'PHI', 'Philadelphia', 'Phillies', 'CLE', 'Cleveland', 'Indians');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-30-2013', 'BOS', 'Boston', 'Red Sox', 'TOR', 'Toronto', 'Blue Jays');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-30-2013', 'MIN', 'Minnesota', 'Twins', 'DET', 'Detroit', 'Tigers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-30-2013', 'NYM', 'New York', 'Mets', 'MIA', 'Miami', 'Marlins');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-30-2013', 'WSH', 'Washington D.C.', 'Nationals', 'ATL', 'Atlanta', 'Braves');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-30-2013', 'CHW', 'Chicago', 'White Sox', 'TEX', 'Texas', 'Rangers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-30-2013', 'SD', 'San Diego', 'Padres', 'CHC', 'Chicago', 'Cubs');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-30-2013', 'PIT', 'Pittsburgh', 'Pirates', 'MIL', 'Milwaukee', 'Brewers');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-30-2013', 'TB', 'Tampa Bay', 'Rays', 'KC', 'Kansas City', 'Royals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-30-2013', 'CIN', 'Cincinatti', 'Reds', 'STL', 'St. Louis', 'Cardinals');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-30-2013', 'SF', 'San Francisco', 'Giants', 'ARI', 'Arizona', 'Diamondbacks');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-30-2013', 'LAA', 'Anaheim', 'Angels', 'OAK', 'Oakland', 'Athletics');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-30-2013', 'BAL', 'Baltimore', 'Orioles', 'SEA', 'Seattle', 'Mariners');
INSERT INTO SCHEDULE_MASTER (DATE, AWAY_TEAM_CITY, AWAY_TEAM_NAME, HOME_TEAM_CITY, HOME_TEAM_NAME) VALUES( '4-30-2013', 'COL', 'Colorado', 'Rockies', 'LAD', 'Los Angeles', 'Dodgers');
